/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/app/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLegalDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sms-challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSmsChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCurrentSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchPreferences"];
        trace?: never;
    };
    "/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptConsents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/home-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHomeOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSelfProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchSelfProfile"];
        trace?: never;
    };
    "/me/life-profile/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSelfProfileRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profile/revisions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewSelfProfileRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profile/revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSelfProfileRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profile/revisions/{revisionId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmSelfProfileRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/registration-reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRegistrationReward"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/registration-reward/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimRegistrationReward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/wisdom-seed-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWisdomSeedAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/wisdom-seed-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWisdomSeedTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generation-tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGenerationTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generation-tasks/{taskId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryGenerationTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generation-tasks/{taskId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamGenerationTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-insights/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOrGetTodayDailyInsight"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDailyInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-insights/{localDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDailyInsightByLocalDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLifeProfiles"];
        put?: never;
        post: operations["createOtherLifeProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLifeProfile"];
        put?: never;
        post?: never;
        delete: operations["deleteLifeProfile"];
        options?: never;
        head?: never;
        patch: operations["patchLifeProfile"];
        trace?: never;
    };
    "/me/life-profiles/{profileId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLifeProfileRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profiles/{profileId}/revisions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewLifeProfileRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profiles/{profileId}/revisions/{revisionId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmLifeProfileRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profile-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLifeProfileGroups"];
        put?: never;
        post: operations["createLifeProfileGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/life-profile-groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteLifeProfileGroup"];
        options?: never;
        head?: never;
        patch: operations["patchLifeProfileGroup"];
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/account-deletion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAccountDeletionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/account-deletion-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountDeletionRequest"];
        put?: never;
        post?: never;
        delete: operations["cancelAccountDeletionRequest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                requestId: string;
                details?: {
                    [key: string]: unknown;
                } | null;
            };
        };
        PageMeta: {
            nextCursor: string | null;
            hasMore: boolean;
        };
        Preferences: {
            /** @example Asia/Shanghai */
            timezone: string;
            timezoneSource?: string;
            /** @example zh-CN */
            locale: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PatchPreferencesRequest: {
            timezone?: string;
            locale?: string;
        };
        PreferencesEnvelope: {
            data: components["schemas"]["Preferences"];
        };
        LegalDocumentSummary: {
            documentId: string;
            /** @enum {string} */
            type: "PRIVACY_POLICY" | "TERMS_OF_SERVICE" | "AI_CONTENT_NOTICE";
            version: string;
            title: string;
            required: boolean;
            /** Format: date-time */
            publishedAt?: string;
        };
        BootstrapEnvelope: {
            data: {
                /** Format: date-time */
                serverTime: string;
                /** @constant */
                apiVersion: "v1";
                configVersion: string;
                maintenance: {
                    enabled: boolean;
                    message: string | null;
                };
                clientPolicy: {
                    minimumSupportedVersion?: string;
                    latestVersion?: string;
                    forceRefresh?: boolean;
                };
                features: {
                    [key: string]: boolean;
                };
                requiredLegalDocuments: components["schemas"]["LegalDocumentSummary"][];
            };
        };
        LegalDocumentEnvelope: {
            data: components["schemas"]["LegalDocumentSummary"] & {
                /** @constant */
                contentFormat: "MARKDOWN";
                content: string;
            };
        };
        CreateSmsChallengeRequest: {
            phone: {
                countryCode: string;
                nationalNumber: string;
            };
            /** @enum {string} */
            purpose: "LOGIN" | "ACCOUNT_DELETION" | "SECURITY_CONFIRMATION";
            device: components["schemas"]["Device"];
        };
        Device: {
            deviceId: string;
            timezone: string;
            appVersion?: string;
        };
        SmsChallengeEnvelope: {
            data: {
                challengeId: string;
                /** Format: date-time */
                expiresAt: string;
                /** Format: date-time */
                resendAvailableAt: string;
                phoneMasked: string;
            };
        };
        ConsentAcceptance: {
            documentId: string;
            version: string;
        };
        CreateSessionRequest: {
            challengeId: string;
            verificationCode: string;
            consentAcceptances: components["schemas"]["ConsentAcceptance"][];
            device: components["schemas"]["Device"];
        };
        UserSummary: {
            userId: string;
            /** @enum {string} */
            status: "ACTIVE" | "DELETION_PENDING" | "DELETING" | "DISABLED";
            phoneMasked: string;
            requiresConsent: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        NextAction: "ACCEPT_CONSENTS" | "CREATE_PROFILE" | "CONFIRM_PROFILE" | "CLAIM_REGISTRATION_REWARD" | "CREATE_TODAY_DAILY_INSIGHT" | "VIEW_HOME";
        SessionEnvelope: {
            data: {
                accessToken: string;
                /** Format: date-time */
                accessTokenExpiresAt: string;
                sessionId: string;
                isNewUser: boolean;
                user: components["schemas"]["UserSummary"];
                nextAction: components["schemas"]["NextAction"];
            };
        };
        RefreshSessionEnvelope: {
            data: {
                accessToken: string;
                /** Format: date-time */
                accessTokenExpiresAt: string;
                sessionId: string;
            };
        };
        MeEnvelope: {
            data: components["schemas"]["UserSummary"] & {
                preferences: components["schemas"]["Preferences"];
                pendingConsents?: components["schemas"]["LegalDocumentSummary"][];
                /** @enum {string} */
                profileState?: "NOT_CREATED" | "CALCULATED" | "ACTIVE";
                nextAction: components["schemas"]["NextAction"];
            };
        };
        AcceptConsentsRequest: {
            acceptances: components["schemas"]["ConsentAcceptance"][];
        };
        ConsentEnvelope: {
            data: {
                records: (components["schemas"]["ConsentAcceptance"] & {
                    /** Format: date-time */
                    acceptedAt?: string;
                })[];
                requiresConsent: boolean;
                nextAction: components["schemas"]["NextAction"];
            };
        };
        HomeOverviewEnvelope: {
            data: {
                user: {
                    userId?: string;
                    timezone?: string;
                };
                profile: components["schemas"]["LifeProfile"];
                cards?: components["schemas"]["RelationshipCard"][];
                registrationReward: components["schemas"]["RegistrationReward"];
                wisdomSeedAccount: components["schemas"]["WisdomSeedAccount"];
                dailyInsight: {
                    /** Format: date */
                    localDate?: string;
                    /** @enum {string} */
                    state?: "NOT_CREATED" | "GENERATING" | "READY" | "FAILED";
                    dailyInsightId?: string | null;
                    taskId?: string | null;
                };
                nextAction: components["schemas"]["NextAction"];
            };
        };
        Location: {
            locationId: string;
            displayName: string;
            countryCode: string;
            administrativePath: string[];
            timezone: string;
            coordinates: {
                latitude: number;
                longitude: number;
            };
        };
        LocationListEnvelope: {
            data: components["schemas"]["Location"][];
            meta: components["schemas"]["PageMeta"];
        };
        BirthInput: {
            /** @enum {string} */
            calendarType: "SOLAR" | "LUNAR";
            date: {
                year: number;
                month: number;
                day: number;
                isLeapMonth: boolean;
            };
            /** @enum {string} */
            timePrecision: "EXACT_MINUTE" | "APPROXIMATE" | "HOUR_RANGE" | "DATE_ONLY";
            time: {
                localTime: string | null;
                /** @enum {string|null} */
                hourBranchCode: "ZI" | "CHOU" | "YIN" | "MAO" | "CHEN" | "SI" | "WU" | "WEI" | "SHEN" | "YOU" | "XU" | "HAI" | null;
            };
            locationId: string;
            /** @enum {string} */
            calculationGender: "MALE" | "FEMALE";
        };
        ProfilePreviewRequest: {
            birthInput: components["schemas"]["BirthInput"];
        };
        ConfirmProfileRevisionRequest: {
            fingerprint: string;
            enhancedConfirmationAccepted: boolean;
        };
        ProfileConfirmation: {
            profileId: string;
            revisionId: string;
            revisionNumber: number;
            /** @constant */
            status: "ACTIVE";
            previousActiveRevisionId?: string | null;
            astrologySnapshotId: string;
            /** Format: date-time */
            confirmedAt: string;
            reportImpact: {
                currentLifeReportStillAvailable: boolean;
                currentLifeReportBasedOnPreviousRevision: boolean;
                newLifeReportCanBeGenerated: boolean;
            };
        };
        ProfileConfirmationEnvelope: {
            data: components["schemas"]["ProfileConfirmation"];
        };
        RelationshipCard: {
            /** @enum {string} */
            dimension: "SPACETIME" | "CAREER" | "FAMILY" | "SELF";
            title: string;
            order: number;
            cardId: number | null;
            cardCode: string;
            ganzhi: string | null;
            zodiac: string | null;
            season: string | null;
            talentMark: string | null;
            abilityMark: string | null;
            journeyMark: string | null;
            deckCode: string;
            deckVersion: string;
            assetUrl: string | null;
            altText: string;
            summary: string;
            uncertainty?: string | null;
            mappingVersion?: string;
            knowledgeVersion?: string;
        };
        LifeProfile: {
            profileId: string;
            subjectId?: string;
            /** @enum {string} */
            subjectType: "SELF" | "OTHER";
            displayName: string;
            /** @enum {string} */
            relationshipType?: "SELF" | "FAMILY" | "FRIEND" | "COLLEAGUE" | "OTHER";
            groupId?: string | null;
            currentRevisionId?: string | null;
            pendingRevisionId?: string | null;
            /** @enum {string} */
            state: "NOT_CREATED" | "CALCULATED" | "ACTIVE" | "DELETED";
            /** Format: date-time */
            updatedAt?: string;
        };
        LifeProfileEnvelope: {
            data: components["schemas"]["LifeProfile"];
        };
        ProfileRevision: {
            revisionId: string;
            revisionNumber: number;
            /** @enum {string} */
            status: "DRAFT" | "CALCULATED" | "ACTIVE" | "SUPERSEDED" | "EXPIRED";
            inputFingerprint?: string;
            originalInput?: components["schemas"]["BirthInput"];
            normalizedBirthData?: {
                [key: string]: unknown;
            };
            calculationPreview?: {
                [key: string]: unknown;
            };
            cards?: components["schemas"]["RelationshipCard"][];
            requiresEnhancedConfirmation?: boolean;
            warnings?: string[];
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            confirmedAt?: string | null;
        };
        ProfileRevisionEnvelope: {
            data: components["schemas"]["ProfileRevision"];
        };
        ProfileRevisionListEnvelope: {
            data: components["schemas"]["ProfileRevision"][];
            meta: components["schemas"]["PageMeta"];
        };
        CreateLifeProfileRequest: {
            displayName: string;
            /** @enum {string} */
            relationshipType: "FAMILY" | "FRIEND" | "COLLEAGUE" | "OTHER";
            groupId?: string | null;
        };
        PatchSelfLifeProfileRequest: {
            displayName: string;
        };
        PatchLifeProfileRequest: {
            displayName?: string;
            /** @enum {string} */
            relationshipType?: "FAMILY" | "FRIEND" | "COLLEAGUE" | "OTHER";
            groupId?: string | null;
        };
        LifeProfileListEnvelope: {
            data: components["schemas"]["LifeProfile"][];
            meta: components["schemas"]["PageMeta"];
        };
        ProfileGroup: {
            groupId: string;
            name: string;
            sortOrder: number;
            profileCount: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpsertProfileGroupRequest: {
            name: string;
            sortOrder: number;
        };
        ProfileGroupEnvelope: {
            data: components["schemas"]["ProfileGroup"];
        };
        ProfileGroupListEnvelope: {
            data: components["schemas"]["ProfileGroup"][];
        };
        WisdomSeedAccount: {
            accountId: string;
            available: number;
            reserved: number;
            totalEarned: number;
            totalSpent: number;
            /** Format: date-time */
            updatedAt: string;
        };
        WisdomSeedAccountEnvelope: {
            data: components["schemas"]["WisdomSeedAccount"];
        };
        WisdomSeedTransaction: {
            transactionId: string;
            /** @enum {string} */
            type: "GRANT" | "RESERVE" | "CONSUME" | "RELEASE" | "REFUND" | "ADJUSTMENT";
            amount: number;
            balanceAfter: number;
            /** @enum {string} */
            businessType: "REGISTRATION_REWARD" | "DAILY_INSIGHT";
            resourceId: string;
            originalTransactionId?: string | null;
            title?: string;
            /** Format: date-time */
            createdAt: string;
        };
        WisdomSeedTransactionListEnvelope: {
            data: components["schemas"]["WisdomSeedTransaction"][];
            meta: components["schemas"]["PageMeta"];
        };
        RegistrationReward: {
            rewardId: string;
            /** @constant */
            rewardType: "NEW_USER_ONBOARDING";
            /** @enum {string} */
            status: "AVAILABLE" | "CLAIMED" | "EXPIRED" | "INELIGIBLE";
            /** @constant */
            wisdomSeedAmount: 3;
            /** Format: date-time */
            claimedAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        RegistrationRewardEnvelope: {
            data: components["schemas"]["RegistrationReward"];
        };
        RegistrationRewardClaimEnvelope: {
            data: {
                reward: components["schemas"]["RegistrationReward"];
                account: components["schemas"]["WisdomSeedAccount"];
                transaction: components["schemas"]["WisdomSeedTransaction"];
            };
        };
        SeedSettlement: {
            /** @constant */
            currency: "WISDOM_SEED";
            /** @constant */
            amount: 1;
            /** @enum {string} */
            status: "RESERVED" | "CONSUMED" | "RELEASED" | "REFUNDED";
            transactionId: string;
        };
        GenerationTask: {
            taskId: string;
            /** @constant */
            type: "DAILY_INSIGHT_GENERATION";
            /** @enum {string} */
            status: "PENDING" | "GENERATING" | "READY" | "FAILED";
            /** @enum {string} */
            stage: "QUEUED" | "PREPARING_PROFILE" | "PREPARING_CONTEXT" | "GENERATING_CONTENT" | "VALIDATING_CONTENT" | "FINALIZING" | "COMPLETED" | "RETRY_WAITING" | "FAILED";
            stageLabel: string;
            canRetry: boolean;
            target: {
                /** @constant */
                type: "DAILY_INSIGHT";
                id: string;
            };
            failure?: {
                code?: string;
                message?: string;
                retryable?: boolean;
            } | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        GenerationTaskEnvelope: {
            data: components["schemas"]["GenerationTask"];
        };
        DailyInsight: {
            dailyInsightId: string;
            /** Format: date */
            localDate: string;
            timezone: string;
            /** @enum {string} */
            status: "GENERATING" | "READY" | "FAILED";
            profileRevisionId?: string | null;
            content?: {
                theme?: string;
                insight?: string;
                action?: string;
                reflectionQuestion?: string;
                notice?: string;
            } | null;
            fallback?: {
                title?: string;
                message?: string;
            } | null;
            taskId?: string | null;
            settlement: components["schemas"]["SeedSettlement"];
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        DailyInsightEnvelope: {
            data: components["schemas"]["DailyInsight"];
        };
        DailyInsightCommandEnvelope: {
            data: {
                dailyInsight: components["schemas"]["DailyInsight"];
                task: components["schemas"]["GenerationTask"] | null;
            };
        };
        DailyInsightListEnvelope: {
            data: components["schemas"]["DailyInsight"][];
            meta: components["schemas"]["PageMeta"];
        };
        CreateFeedbackRequest: {
            target: {
                /** @enum {string} */
                type: "LIFE_REPORT" | "DAILY_INSIGHT";
                id: string;
                sectionCode?: string | null;
            };
            /** @enum {string} */
            rating: "HELPFUL" | "NOT_RESONANT" | "UNCOMFORTABLE";
            reasons: ("TOO_ABSOLUTE" | "NOT_ACCURATE" | "TOO_GENERIC" | "HARMFUL_OR_OFFENSIVE" | "OTHER")[];
            comment?: string | null;
        };
        FeedbackEnvelope: {
            data: {
                feedbackId: string;
                target: {
                    [key: string]: unknown;
                };
                rating: string;
                /** Format: date-time */
                createdAt: string;
            };
        };
        CreateAccountDeletionRequest: {
            smsChallengeId: string;
            verificationCode: string;
            /** @enum {string} */
            reason: "NO_LONGER_NEEDED" | "PRIVACY_CONCERN" | "OTHER";
        };
        AccountDeletion: {
            requestId: string;
            /** @enum {string} */
            status: "PENDING" | "DELETING" | "COMPLETED" | "PARTIAL_FAILURE" | "CANCELLED";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            scheduledExecutionAt?: string | null;
            canCancel: boolean;
        };
        AccountDeletionEnvelope: {
            data: components["schemas"]["AccountDeletion"];
        };
        DeletionAcceptedEnvelope: {
            data: {
                requestId: string;
                /** @constant */
                status: "PENDING";
            };
        };
    };
    responses: {
        /** @description API v1 error */
        Error: {
            headers: {
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        Cursor: string;
        Limit: number;
        ProfileId: string;
        RevisionId: string;
        TaskId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getLegalDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published legal document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalDocumentEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createSmsChallenge: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSmsChallengeRequest"];
            };
        };
        responses: {
            /** @description Challenge accepted */
            202: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsChallengeEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created; refresh token is only set as a secure cookie. */
            201: {
                headers: {
                    /** @description satori_refresh HttpOnly; Secure; SameSite=Lax */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access token refreshed and refresh cookie rotated. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshSessionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and refresh cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user routing state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patchPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPreferencesRequest"];
            };
        };
        responses: {
            /** @description Updated preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    acceptConsents: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptConsentsRequest"];
            };
        };
        responses: {
            /** @description Consent records created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getHomeOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable R1.0 home projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeOverviewEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    searchLocations: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Standard locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSelfProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current self profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifeProfileEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patchSelfProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSelfLifeProfileRequest"];
            };
        };
        responses: {
            /** @description Updated self profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifeProfileEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSelfProfileRevisions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revision history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRevisionListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    previewSelfProfileRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePreviewRequest"];
            };
        };
        responses: {
            /** @description Calculated preview revision */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRevisionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSelfProfileRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRevisionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    confirmSelfProfileRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmProfileRevisionRequest"];
            };
        };
        responses: {
            /** @description Revision activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileConfirmationEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRegistrationReward: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration reward eligibility and status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationRewardEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    claimRegistrationReward: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Reward claimed or original claim replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationRewardClaimEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWisdomSeedAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wisdom seed account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WisdomSeedAccountEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listWisdomSeedTransactions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wisdom seed ledger */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WisdomSeedTransactionListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGenerationTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persistent task state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationTaskEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    retryGenerationTask: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Retry accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationTaskEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamGenerationTaskEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE snapshot, stage, retry, ready, failed and heartbeat events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createOrGetTodayDailyInsight: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Existing ready insight */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInsightCommandEnvelope"];
                };
            };
            /** @description Generation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInsightCommandEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDailyInsights: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily insight history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInsightListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDailyInsightByLocalDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                localDate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insight for local date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInsightEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listLifeProfiles: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifeProfileListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createOtherLifeProfile: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLifeProfileRequest"];
            };
        };
        responses: {
            /** @description OTHER profile created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifeProfileEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getLifeProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifeProfileEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteLifeProfile: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionAcceptedEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patchLifeProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchLifeProfileRequest"];
            };
        };
        responses: {
            /** @description Profile metadata updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifeProfileEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listLifeProfileRevisions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile revisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRevisionListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    previewLifeProfileRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePreviewRequest"];
            };
        };
        responses: {
            /** @description Calculated preview */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRevisionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    confirmLifeProfileRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmProfileRevisionRequest"];
            };
        };
        responses: {
            /** @description Revision activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRevisionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listLifeProfileGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGroupListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createLifeProfileGroup: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProfileGroupRequest"];
            };
        };
        responses: {
            /** @description Group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGroupEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteLifeProfileGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group deleted; profiles retained and ungrouped */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    patchLifeProfileGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProfileGroupRequest"];
            };
        };
        responses: {
            /** @description Group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGroupEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedbackRequest"];
            };
        };
        responses: {
            /** @description Feedback created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAccountDeletionRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountDeletionRequest"];
            };
        };
        responses: {
            /** @description Deletion accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAccountDeletionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current deletion request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelAccountDeletionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion request cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
