import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import Fastify from 'fastify';
import { SignJWT, jwtVerify } from 'jose';
import { createDecipheriv, createHmac, randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import pg from 'pg';
import { z } from 'zod';
import { authenticateOperationsAccount, parseOperationsAccounts } from './accounts.js';

const { Pool } = pg;
const env=z.object({DATABASE_URL:z.string().min(1),OPERATIONS_JWT_SECRET:z.string().min(32),OPERATIONS_ACCOUNTS_JSON:z.string().optional(),OPERATIONS_BOOTSTRAP_USER:z.string().min(3).optional(),OPERATIONS_BOOTSTRAP_PASSWORD_SHA256:z.string().length(64).optional(),AUTH_HMAC_SECRET:z.string().min(32),DATA_ENCRYPTION_KEY:z.string().length(64),SATORI_API_BASE:z.string().url(),SATORI_OPERATOR_TOKEN:z.string().min(20).optional(),PORT:z.coerce.number().default(3210),OPERATIONS_CORS_ORIGIN:z.string().default('https://operations.test.shenxinyou.com')}).parse(process.env);
const operationsAccounts=parseOperationsAccounts(env);
const pool=new Pool({connectionString:env.DATABASE_URL,max:10});
const app=Fastify({logger:true,requestIdHeader:'x-request-id'});
await app.register(helmet); await app.register(cors,{origin:env.OPERATIONS_CORS_ORIGIN.split(',')});
const secret=new TextEncoder().encode(env.OPERATIONS_JWT_SECRET);
const stateCn:Record<string,string>={ACTIVE:'生效中',INACTIVE:'已停用',DRAFT:'草稿',PUBLISHED:'已发布',RETIRED:'已归档',PENDING_PAYMENT:'待支付',PAYMENT_PROCESSING:'支付确认中',PAID:'支付成功',FULFILLING:'权益到账中',FULFILLED:'已到账',EXCEPTION:'到账异常',OPEN:'待处理',RESOLVED:'已解决'};
const operationRoles=['SUPER_ADMIN','PRODUCT_OPERATOR','USER_OPERATOR','CUSTOMER_SERVICE','FINANCE','TECH_ADMIN'] as const;
const operationRoleCn:Record<(typeof operationRoles)[number],string>={SUPER_ADMIN:'超级管理员',PRODUCT_OPERATOR:'产品运营',USER_OPERATOR:'用户运营',CUSTOMER_SERVICE:'客服',FINANCE:'财务',TECH_ADMIN:'技术管理员'};
const passwordDigest=(password:string,salt:string)=>scryptSync(password,salt,64);
const phoneHash=(phone:string)=>createHmac('sha256',env.AUTH_HMAC_SECRET).update(`phone:+86${phone}`).digest('hex');
const decrypt=(value?:string|null)=>{if(!value)return '';try{const [iv,tag,ciphertext]=value.split('.'),decipher=createDecipheriv('aes-256-gcm',Buffer.from(env.DATA_ENCRYPTION_KEY,'hex'),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(ciphertext,'base64url')),decipher.final()]).toString('utf8')}catch{return ''}};
const userIdentity=(row:any)=>({user_id:row.owner_user_id||row.actor_user_id||row.user_id||row.id,phone_masked:row.phone_masked||'未绑定手机号',nickname:decrypt(row.display_name_ciphertext)||'未设置昵称'});
const withUserIdentity=(rows:Record<string,unknown>[])=>rows.map(row=>({...row,user:userIdentity(row)}));
const accountView=(account:any)=>({id:account.id,phone:account.phone,nickname:account.nickname,status:account.status,created_at:account.created_at,password_changed_at:account.password_changed_at,roles:(account.roles||[]).map((role:string)=>({code:role,name:operationRoleCn[role as keyof typeof operationRoleCn]||role}))});
const requireSuperAdmin=(req:any,reply:any)=>{if(!Array.isArray(req.operator?.roles)||!req.operator.roles.includes('SUPER_ADMIN')){reply.code(403).send({code:'SUPER_ADMIN_REQUIRED',message:'仅超级管理员可以管理运营账号和角色'});return false}return true};
app.addHook('preHandler',async(req,reply)=>{if(req.url==='/health/ready'||req.url==='/api/auth/login')return;const raw=req.headers.authorization?.replace(/^Bearer\s+/,'');if(!raw)return reply.code(401).send({code:'UNAUTHORIZED',message:'请先登录运营平台'});try{const {payload}=await jwtVerify(raw,secret,{audience:'fresh-operations'});(req as any).operator=payload;}catch{return reply.code(401).send({code:'TOKEN_INVALID',message:'登录已失效，请重新登录'});}});
const rows=async<T=Record<string,unknown>>(sql:string,args:unknown[]=[])=>(await pool.query<T&pg.QueryResultRow>(sql,args)).rows;
await pool.query(`create table if not exists operations_action_requests(
 id uuid primary key,action_type text not null,status text not null check(status in('PENDING','APPROVED','REJECTED','EXECUTED','FAILED')),
 payload jsonb not null,reason text not null,submitted_by text not null,reviewed_by text,review_note text,idempotency_key text not null unique,
 execution_result jsonb,created_at timestamptz not null default now(),reviewed_at timestamptz,executed_at timestamptz
)`);
await pool.query(`create table if not exists operations_accounts(
 id uuid primary key,phone varchar(20) not null unique,nickname varchar(50) not null,password_salt varchar(64) not null,password_hash varchar(128) not null,
 status text not null default 'ACTIVE' check(status in('ACTIVE','DISABLED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),password_changed_at timestamptz
)`);
await pool.query(`create table if not exists operations_account_roles(
 account_id uuid not null references operations_accounts(id) on delete cascade,role text not null,created_at timestamptz not null default now(),primary key(account_id,role)
)`);
app.get('/health/ready',async()=>{await pool.query('select 1');return {status:'ready'}});
app.post('/api/auth/login',async(req,reply)=>{const input=z.object({account:z.string().min(1),password:z.string().min(1)}).parse(req.body);const [account]=await rows<any>(`select a.*,coalesce(array_agg(r.role) filter(where r.role is not null),'{}') roles from operations_accounts a left join operations_account_roles r on r.account_id=a.id where a.phone=$1 group by a.id`,[input.account]);if(account){const actual=passwordDigest(input.password,account.password_salt),expected=Buffer.from(account.password_hash,'hex');if(account.status!=='ACTIVE'||expected.length!==actual.length||!timingSafeEqual(expected,actual))return reply.code(401).send({code:'LOGIN_FAILED',message:'账号或密码不正确'});const token=await new SignJWT({name:account.nickname,phone:account.phone,accountId:account.id,roles:account.roles}).setProtectedHeader({alg:'HS256'}).setSubject(account.phone).setAudience('fresh-operations').setIssuedAt().setExpirationTime('8h').sign(secret);return {data:{token,operator:accountView(account)}}}const configured=authenticateOperationsAccount(operationsAccounts,input.account,input.password);if(!configured)return reply.code(401).send({code:'LOGIN_FAILED',message:'账号或密码不正确'});const token=await new SignJWT({name:configured.account,roles:['SUPER_ADMIN'],bootstrap:true}).setProtectedHeader({alg:'HS256'}).setSubject(configured.account).setAudience('fresh-operations').setIssuedAt().setExpirationTime('8h').sign(secret);return {data:{token,operator:{name:configured.account,nickname:configured.account,roles:[{code:'SUPER_ADMIN',name:'超级管理员'}]}}}});
app.get('/api/dashboard',async()=>{const [s]=await rows<any>(`select (select count(*) from users) total_users,(select count(*) from users where created_at>=current_date) new_users,(select coalesce(sum(amount_minor),0) from money_orders where status in('PAID','FULFILLING','FULFILLED')) revenue_minor,(select count(*) from money_orders where status='PENDING_PAYMENT') pending_orders,(select count(*) from reconciliation_cases where status='OPEN') open_cases,(select count(*) from reconciliation_cases where status='OPEN' and severity='CRITICAL') critical_cases`);return {data:s}});
app.get('/api/meta/operation-roles',async()=>({data:operationRoles.map(code=>({code,name:operationRoleCn[code]}))}));
app.get('/api/me',async(req)=>{const operator=(req as any).operator;if(operator.bootstrap)return {data:{phone:null,nickname:operator.name,roles:[{code:'SUPER_ADMIN',name:'超级管理员'}],bootstrap:true}};const [account]=await rows<any>(`select a.*,coalesce(array_agg(r.role) filter(where r.role is not null),'{}') roles from operations_accounts a left join operations_account_roles r on r.account_id=a.id where a.id=$1 group by a.id`,[operator.accountId]);return {data:account?accountView(account):null}});
app.patch('/api/me',async(req,reply)=>{const operator=(req as any).operator;if(operator.bootstrap)return reply.code(409).send({code:'BOOTSTRAP_ACCOUNT_IMMUTABLE',message:'引导管理员请通过服务器安全配置修改资料'});const input=z.object({nickname:z.string().min(2).max(50).optional(),currentPassword:z.string().min(8).optional(),newPassword:z.string().min(8).max(72).optional()}).refine(x=>!x.newPassword||Boolean(x.currentPassword),{message:'修改密码需要输入当前密码'}).parse(req.body);const [account]=await rows<any>('select * from operations_accounts where id=$1',[operator.accountId]);if(!account)return reply.code(404).send({code:'ACCOUNT_NOT_FOUND',message:'运营账号不存在'});if(input.newPassword){const actual=passwordDigest(input.currentPassword!,account.password_salt),expected=Buffer.from(account.password_hash,'hex');if(expected.length!==actual.length||!timingSafeEqual(expected,actual))return reply.code(400).send({code:'PASSWORD_MISMATCH',message:'当前密码不正确'});const salt=randomBytes(16).toString('hex'),hash=passwordDigest(input.newPassword,salt).toString('hex');await pool.query('update operations_accounts set nickname=coalesce($2,nickname),password_salt=$3,password_hash=$4,password_changed_at=now(),updated_at=now() where id=$1',[account.id,input.nickname||null,salt,hash])}else if(input.nickname)await pool.query('update operations_accounts set nickname=$2,updated_at=now() where id=$1',[account.id,input.nickname]);return {data:{updated:true}}});
app.get('/api/accounts',async(req,reply)=>{if(!requireSuperAdmin(req,reply))return;return {data:(await rows<any>(`select a.*,coalesce(array_agg(r.role) filter(where r.role is not null),'{}') roles from operations_accounts a left join operations_account_roles r on r.account_id=a.id group by a.id order by a.created_at desc`)).map(accountView)}});
app.post('/api/accounts',async(req,reply)=>{if(!requireSuperAdmin(req,reply))return;const input=z.object({phone:z.string().regex(/^1\d{10}$/),nickname:z.string().min(2).max(50),roles:z.array(z.enum(operationRoles)).min(1)}).parse(req.body);const id=randomUUID(),initialPassword=`Fresh-${randomBytes(5).toString('hex')}`,salt=randomBytes(16).toString('hex'),hash=passwordDigest(initialPassword,salt).toString('hex'),client=await pool.connect();try{await client.query('begin');const created=await client.query<any>('insert into operations_accounts(id,phone,nickname,password_salt,password_hash) values($1,$2,$3,$4,$5) returning *',[id,input.phone,input.nickname,salt,hash]);for(const role of [...new Set(input.roles)])await client.query('insert into operations_account_roles(account_id,role) values($1,$2)',[id,role]);await client.query('commit');return reply.code(201).send({data:{account:accountView({...created.rows[0],roles:input.roles}),initialPassword}})}catch(error){await client.query('rollback');if((error as any)?.code==='23505')return reply.code(409).send({code:'PHONE_ALREADY_EXISTS',message:'该手机号已创建运营账号'});throw error}finally{client.release()}});
app.patch('/api/accounts/:id/roles',async(req,reply)=>{if(!requireSuperAdmin(req,reply))return;const id=(req.params as any).id,input=z.object({roles:z.array(z.enum(operationRoles)).min(1),status:z.enum(['ACTIVE','DISABLED']).optional()}).parse(req.body),client=await pool.connect();try{await client.query('begin');await client.query('delete from operations_account_roles where account_id=$1',[id]);for(const role of [...new Set(input.roles)])await client.query('insert into operations_account_roles(account_id,role) values($1,$2)',[id,role]);if(input.status)await client.query('update operations_accounts set status=$2,updated_at=now() where id=$1',[id,input.status]);await client.query('commit');return {data:{updated:true}}}catch(error){await client.query('rollback');throw error}finally{client.release()}});
app.get('/api/users',async(req)=>{const q=String((req.query as any).q||'').trim(),hash=/^1\d{10}$/.test(q)?phoneHash(q):'';const found=await rows<any>(`select u.id,u.status,u.created_at,i.phone_masked,s.display_name_ciphertext,coalesce(sum(g.available_quantity),0)::int seed_balance from users u left join identities i on i.user_id=u.id and i.provider='PHONE' left join lateral(select display_name_ciphertext from subjects where owner_user_id=u.id and type='SELF' and deleted_at is null order by created_at limit 1)s on true left join complimentary_seed_grants g on g.owner_user_id=u.id and g.status='ACTIVE' where ($1='' or i.phone_masked ilike '%'||$1||'%' or i.provider_subject_hash=$2 or u.id::text=$1 or right(replace(u.id::text,'-',''),6)=upper(replace($1,'FRESH-',''))) group by u.id,i.phone_masked,s.display_name_ciphertext order by u.created_at desc limit 100`,[q,hash]);return {data:found.map(x=>({...x,nickname:decrypt(x.display_name_ciphertext)}))}});
app.get('/api/users/:id',async(req)=>{const id=(req.params as any).id;const [user]=await rows<any>(`select u.id,u.status,u.created_at,i.phone_masked,s.display_name_ciphertext from users u left join identities i on i.user_id=u.id and i.provider='PHONE' left join lateral(select display_name_ciphertext from subjects where owner_user_id=u.id and type='SELF' and deleted_at is null order by created_at limit 1)s on true where u.id=$1`,[id]);if(!user)return {data:null};const [orders,seeds,rights,memberships]=await Promise.all([rows('select id,order_number,status,amount_minor,created_at from money_orders where owner_user_id=$1 order by created_at desc',[id]),rows('select id,total_quantity,available_quantity,status,expires_at from complimentary_seed_grants where owner_user_id=$1 order by created_at desc',[id]),rows('select id,service_type,total_quantity,available_quantity,status,expires_at from entitlement_grants where owner_user_id=$1 order by created_at desc',[id]),rows('select id,status,starts_at,ends_at from membership_subscriptions where owner_user_id=$1 order by created_at desc',[id])]);return {data:{...user,nickname:decrypt(user.display_name_ciphertext),orders,seeds,entitlements:rights,memberships}}});
app.get('/api/benefits',async()=>{const found=await rows<any>(`select x.*,i.phone_masked,s.display_name_ciphertext from (select '智慧种子' kind,g.id,g.owner_user_id,g.total_quantity,g.available_quantity,g.status,g.expires_at from complimentary_seed_grants g union all select '服务权益',e.id,e.owner_user_id,e.total_quantity,e.available_quantity,e.status,e.expires_at from entitlement_grants e)x left join identities i on i.user_id=x.owner_user_id and i.provider='PHONE' left join lateral(select display_name_ciphertext from subjects where owner_user_id=x.owner_user_id and type='SELF' and deleted_at is null order by created_at limit 1)s on true order by x.expires_at desc nulls last limit 200`);return {data:withUserIdentity(found)}});
app.get('/api/products',async()=>({data:await rows(`select o.id,o.code,o.offering_kind,o.service_type,o.status,v.id version_id,v.version,v.display_name,v.description,v.amount_minor,v.validity_days,v.entitlement_spec,r.minimum_seed_balance,r.reserved_seed_quantity,r.activity_amount_minor from service_offerings o left join offering_versions v on v.id=o.current_version_id left join seed_promotion_rules r on r.offering_version_id=v.id and r.status='ACTIVE' where o.business_space='SATORI' order by o.created_at desc`)}));
app.get('/api/orders',async()=>{const found=await rows<any>(`select o.id,o.order_number,o.owner_user_id,o.status,o.amount_minor,o.created_at,v.display_name,coalesce(f.status,'未创建') fulfillment_status,i.phone_masked,s.display_name_ciphertext from money_orders o join offering_versions v on v.id=o.offering_version_id left join fulfillment_jobs f on f.order_id=o.id left join identities i on i.user_id=o.owner_user_id and i.provider='PHONE' left join lateral(select display_name_ciphertext from subjects where owner_user_id=o.owner_user_id and type='SELF' and deleted_at is null order by created_at limit 1)s on true order by o.created_at desc limit 200`);return {data:withUserIdentity(found)}});
app.get('/api/reconciliation',async()=>({data:await rows(`select * from reconciliation_cases order by detected_at desc limit 200`)}));
app.get('/api/audit',async()=>{const found=await rows<any>(`select a.id,a.actor_user_id,a.action,a.resource_type,a.resource_id,a.metadata,a.created_at,i.phone_masked,s.display_name_ciphertext from audit_logs a left join identities i on i.user_id=a.actor_user_id and i.provider='PHONE' left join lateral(select display_name_ciphertext from subjects where owner_user_id=a.actor_user_id and type='SELF' and deleted_at is null order by created_at limit 1)s on true order by a.created_at desc limit 300`);return {data:found.map(x=>({...x,actor:x.actor_user_id?userIdentity(x):{user_id:null,phone_masked:'系统',nickname:'系统'}}))}});
app.get('/api/roles',async()=>({data:await rows(`select r.id,r.user_id,r.role,r.granted_at,i.phone_masked from operator_roles r left join identities i on i.user_id=r.user_id where r.revoked_at is null order by r.granted_at desc`)}));
app.get('/api/action-requests',async()=>({data:await rows(`select * from operations_action_requests order by created_at desc limit 200`)}));
app.post('/api/action-requests',async(req,reply)=>{const operator=(req as any).operator;const input=z.object({actionType:z.enum(['SEED_ADJUSTMENT','ENTITLEMENT_ADJUSTMENT','RECONCILIATION_RESOLVE','PRODUCT_CHANGE']),payload:z.record(z.string(),z.unknown()),reason:z.string().min(3),idempotencyKey:z.string().min(8).optional()}).parse(req.body);const id=randomUUID(),key=input.idempotencyKey||randomUUID();const [created]=await rows(`insert into operations_action_requests(id,action_type,status,payload,reason,submitted_by,idempotency_key) values($1,$2,'PENDING',$3,$4,$5,$6) on conflict(idempotency_key) do update set idempotency_key=excluded.idempotency_key returning *`,[id,input.actionType,input.payload,input.reason,operator.sub,key]);return reply.code(201).send({data:created})});
app.post('/api/action-requests/:id/reject',async(req)=>{const operator=(req as any).operator,input=z.object({note:z.string().min(3)}).parse(req.body),id=(req.params as any).id;const [updated]=await rows(`update operations_action_requests set status='REJECTED',reviewed_by=$2,review_note=$3,reviewed_at=now() where id=$1 and status='PENDING' returning *`,[id,operator.sub,input.note]);return {data:updated||null}});
app.post('/api/action-requests/:id/approve',async(req,reply)=>{const operator=(req as any).operator,input=z.object({note:z.string().min(3)}).parse(req.body),id=(req.params as any).id;if(!env.SATORI_OPERATOR_TOKEN)return reply.code(503).send({code:'OPERATOR_CREDENTIAL_NOT_CONFIGURED',message:'运营执行凭据尚未配置，申请将保留为待审核状态'});const client=await pool.connect();try{await client.query('begin');const found=await client.query<any>(`select * from operations_action_requests where id=$1 for update`,[id]);const action=found.rows[0];if(!action)return reply.code(404).send({code:'NOT_FOUND',message:'申请不存在'});if(action.status!=='PENDING')return reply.code(409).send({code:'ALREADY_REVIEWED',message:'该申请已经处理'});if(action.submitted_by===operator.sub)return reply.code(409).send({code:'FOUR_EYES_REQUIRED',message:'提交人不能审核自己的高风险操作'});await client.query(`update operations_action_requests set status='APPROVED',reviewed_by=$2,review_note=$3,reviewed_at=now() where id=$1`,[id,operator.sub,input.note]);const p=action.payload as Record<string,unknown>;let path='';if(action.action_type==='SEED_ADJUSTMENT')path=`/api/v1/operations/commerce/seeds/${p.grantId}/adjustments`;else if(action.action_type==='ENTITLEMENT_ADJUSTMENT')path=`/api/v1/operations/commerce/entitlements/${p.grantId}/adjustments`;else if(action.action_type==='RECONCILIATION_RESOLVE')path=`/api/v1/operations/commerce/reconciliation-cases/${p.caseId}/resolve`;else return reply.code(422).send({code:'MANUAL_EXECUTION_REQUIRED',message:'商品配置需经版本发布流程执行'});const response=await fetch(`${env.SATORI_API_BASE}${path}`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${env.SATORI_OPERATOR_TOKEN}`,'x-request-id':action.idempotency_key},body:JSON.stringify(p)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`R1.1 service rejected operation: ${response.status}`);await client.query(`update operations_action_requests set status='EXECUTED',execution_result=$2,executed_at=now() where id=$1`,[id,result]);await client.query('commit');return {data:{...action,status:'EXECUTED',execution_result:result}}}catch(error){await client.query('rollback');await pool.query(`update operations_action_requests set status='FAILED',execution_result=$2,executed_at=now() where id=$1`,[id,{message:error instanceof Error?error.message:'执行失败'}]);throw error}finally{client.release()}});
app.get('/api/meta/status-labels',async()=>({data:stateCn}));
app.setErrorHandler((error,_req,reply)=>{app.log.error(error);reply.code(500).send({code:'OPERATIONS_ERROR',message:'暂时无法完成操作，请稍后重试'})});
await app.listen({port:env.PORT,host:'0.0.0.0'});
