import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import Fastify from 'fastify';
import { SignJWT, jwtVerify } from 'jose';
import { createHash, randomUUID, timingSafeEqual } from 'node:crypto';
import pg from 'pg';
import { z } from 'zod';

const { Pool } = pg;
const env=z.object({DATABASE_URL:z.string().min(1),OPERATIONS_JWT_SECRET:z.string().min(32),OPERATIONS_BOOTSTRAP_USER:z.string().min(3),OPERATIONS_BOOTSTRAP_PASSWORD_SHA256:z.string().length(64),SATORI_API_BASE:z.string().url(),SATORI_OPERATOR_TOKEN:z.string().min(20),PORT:z.coerce.number().default(3210),OPERATIONS_CORS_ORIGIN:z.string().default('https://operations.shenxinyou.com')}).parse(process.env);
const pool=new Pool({connectionString:env.DATABASE_URL,max:10});
const app=Fastify({logger:true,requestIdHeader:'x-request-id'});
await app.register(helmet); await app.register(cors,{origin:env.OPERATIONS_CORS_ORIGIN.split(',')});
const secret=new TextEncoder().encode(env.OPERATIONS_JWT_SECRET);
const stateCn:Record<string,string>={ACTIVE:'生效中',INACTIVE:'已停用',DRAFT:'草稿',PUBLISHED:'已发布',RETIRED:'已归档',PENDING_PAYMENT:'待支付',PAYMENT_PROCESSING:'支付确认中',PAID:'支付成功',FULFILLING:'权益到账中',FULFILLED:'已到账',EXCEPTION:'到账异常',OPEN:'待处理',RESOLVED:'已解决'};
app.addHook('preHandler',async(req,reply)=>{if(req.url==='/health/ready'||req.url==='/api/auth/login')return;const raw=req.headers.authorization?.replace(/^Bearer\s+/,'');if(!raw)return reply.code(401).send({code:'UNAUTHORIZED',message:'请先登录运营平台'});try{const {payload}=await jwtVerify(raw,secret,{audience:'fresh-operations'});(req as any).operator=payload;}catch{return reply.code(401).send({code:'TOKEN_INVALID',message:'登录已失效，请重新登录'});}});
const rows=async<T=Record<string,unknown>>(sql:string,args:unknown[]=[])=>(await pool.query<T&pg.QueryResultRow>(sql,args)).rows;
await pool.query(`create table if not exists operations_action_requests(
 id uuid primary key,action_type text not null,status text not null check(status in('PENDING','APPROVED','REJECTED','EXECUTED','FAILED')),
 payload jsonb not null,reason text not null,submitted_by text not null,reviewed_by text,review_note text,idempotency_key text not null unique,
 execution_result jsonb,created_at timestamptz not null default now(),reviewed_at timestamptz,executed_at timestamptz
)`);
app.get('/health/ready',async()=>{await pool.query('select 1');return {status:'ready'}});
app.post('/api/auth/login',async(req,reply)=>{const input=z.object({account:z.string(),password:z.string()}).parse(req.body);const actual=createHash('sha256').update(input.password).digest();const expected=Buffer.from(env.OPERATIONS_BOOTSTRAP_PASSWORD_SHA256,'hex');if(input.account!==env.OPERATIONS_BOOTSTRAP_USER||expected.length!==actual.length||!timingSafeEqual(expected,actual))return reply.code(401).send({code:'LOGIN_FAILED',message:'账号或密码不正确'});const token=await new SignJWT({name:input.account,roles:['ADMIN']}).setProtectedHeader({alg:'HS256'}).setSubject(input.account).setAudience('fresh-operations').setIssuedAt().setExpirationTime('8h').sign(secret);return {data:{token,operator:{name:input.account,roles:['超级管理员']}}}});
app.get('/api/dashboard',async()=>{const [s]=await rows<any>(`select (select count(*) from users where created_at>=current_date) new_users,(select count(*) from money_orders where status='PENDING_PAYMENT') pending_orders,(select count(*) from reconciliation_cases where status='OPEN') open_cases,(select count(*) from reconciliation_cases where status='OPEN' and severity='CRITICAL') critical_cases`);return {data:s}});
app.get('/api/users',async(req)=>{const q=String((req.query as any).q||'');return {data:await rows(`select u.id,u.status,u.created_at,i.phone_masked,coalesce(sum(g.available_quantity),0)::int seed_balance from users u left join identities i on i.user_id=u.id left join complimentary_seed_grants g on g.owner_user_id=u.id and g.status='ACTIVE' where ($1='' or i.phone_masked ilike '%'||$1||'%' or u.id::text=$1) group by u.id,i.phone_masked order by u.created_at desc limit 100`,[q])}});
app.get('/api/users/:id',async(req)=>{const id=(req.params as any).id;const [user]=await rows(`select u.id,u.status,u.created_at,i.phone_masked from users u left join identities i on i.user_id=u.id where u.id=$1`,[id]);if(!user)return {data:null};const [orders,seeds,rights,memberships]=await Promise.all([rows('select id,order_number,status,amount_minor,created_at from money_orders where owner_user_id=$1 order by created_at desc',[id]),rows('select id,total_quantity,available_quantity,status,expires_at from complimentary_seed_grants where owner_user_id=$1 order by created_at desc',[id]),rows('select id,service_type,total_quantity,available_quantity,status,expires_at from entitlement_grants where owner_user_id=$1 order by created_at desc',[id]),rows('select id,status,starts_at,ends_at from membership_subscriptions where owner_user_id=$1 order by created_at desc',[id])]);return {data:{...user,orders,seeds,entitlements:rights,memberships}}});
app.get('/api/benefits',async()=>({data:await rows(`select '智慧种子' kind,g.id,g.owner_user_id,g.total_quantity,g.available_quantity,g.status,g.expires_at from complimentary_seed_grants g union all select '服务权益',e.id,e.owner_user_id,e.total_quantity,e.available_quantity,e.status,e.expires_at from entitlement_grants e order by expires_at desc nulls last limit 200`)}));
app.get('/api/products',async()=>({data:await rows(`select o.id,o.code,o.offering_kind,o.service_type,o.status,v.id version_id,v.version,v.display_name,v.description,v.amount_minor,v.validity_days,v.entitlement_spec,r.minimum_seed_balance,r.reserved_seed_quantity,r.activity_amount_minor from service_offerings o left join offering_versions v on v.id=o.current_version_id left join seed_promotion_rules r on r.offering_version_id=v.id and r.status='ACTIVE' where o.business_space='SATORI' order by o.created_at desc`)}));
app.get('/api/orders',async()=>({data:await rows(`select o.id,o.order_number,o.owner_user_id,o.status,o.amount_minor,o.created_at,v.display_name,coalesce(f.status,'未创建') fulfillment_status from money_orders o join offering_versions v on v.id=o.offering_version_id left join fulfillment_jobs f on f.order_id=o.id order by o.created_at desc limit 200`)}));
app.get('/api/reconciliation',async()=>({data:await rows(`select * from reconciliation_cases order by detected_at desc limit 200`)}));
app.get('/api/audit',async()=>({data:await rows(`select id,actor_user_id,action,resource_type,resource_id,metadata,created_at from audit_logs order by created_at desc limit 300`)}));
app.get('/api/roles',async()=>({data:await rows(`select r.id,r.user_id,r.role,r.granted_at,i.phone_masked from operator_roles r left join identities i on i.user_id=r.user_id where r.revoked_at is null order by r.granted_at desc`)}));
app.get('/api/action-requests',async()=>({data:await rows(`select * from operations_action_requests order by created_at desc limit 200`)}));
app.post('/api/action-requests',async(req,reply)=>{const operator=(req as any).operator;const input=z.object({actionType:z.enum(['SEED_ADJUSTMENT','ENTITLEMENT_ADJUSTMENT','RECONCILIATION_RESOLVE','PRODUCT_CHANGE']),payload:z.record(z.string(),z.unknown()),reason:z.string().min(3),idempotencyKey:z.string().min(8).optional()}).parse(req.body);const id=randomUUID(),key=input.idempotencyKey||randomUUID();const [created]=await rows(`insert into operations_action_requests(id,action_type,status,payload,reason,submitted_by,idempotency_key) values($1,$2,'PENDING',$3,$4,$5,$6) on conflict(idempotency_key) do update set idempotency_key=excluded.idempotency_key returning *`,[id,input.actionType,input.payload,input.reason,operator.sub,key]);return reply.code(201).send({data:created})});
app.post('/api/action-requests/:id/reject',async(req)=>{const operator=(req as any).operator,input=z.object({note:z.string().min(3)}).parse(req.body),id=(req.params as any).id;const [updated]=await rows(`update operations_action_requests set status='REJECTED',reviewed_by=$2,review_note=$3,reviewed_at=now() where id=$1 and status='PENDING' returning *`,[id,operator.sub,input.note]);return {data:updated||null}});
app.post('/api/action-requests/:id/approve',async(req,reply)=>{const operator=(req as any).operator,input=z.object({note:z.string().min(3)}).parse(req.body),id=(req.params as any).id;const client=await pool.connect();try{await client.query('begin');const found=await client.query<any>(`select * from operations_action_requests where id=$1 for update`,[id]);const action=found.rows[0];if(!action)return reply.code(404).send({code:'NOT_FOUND',message:'申请不存在'});if(action.status!=='PENDING')return reply.code(409).send({code:'ALREADY_REVIEWED',message:'该申请已经处理'});if(action.submitted_by===operator.sub)return reply.code(409).send({code:'FOUR_EYES_REQUIRED',message:'提交人不能审核自己的高风险操作'});await client.query(`update operations_action_requests set status='APPROVED',reviewed_by=$2,review_note=$3,reviewed_at=now() where id=$1`,[id,operator.sub,input.note]);const p=action.payload as Record<string,unknown>;let path='';if(action.action_type==='SEED_ADJUSTMENT')path=`/api/v1/operations/commerce/seeds/${p.grantId}/adjustments`;else if(action.action_type==='ENTITLEMENT_ADJUSTMENT')path=`/api/v1/operations/commerce/entitlements/${p.grantId}/adjustments`;else if(action.action_type==='RECONCILIATION_RESOLVE')path=`/api/v1/operations/commerce/reconciliation-cases/${p.caseId}/resolve`;else return reply.code(422).send({code:'MANUAL_EXECUTION_REQUIRED',message:'商品配置需经版本发布流程执行'});const response=await fetch(`${env.SATORI_API_BASE}${path}`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${env.SATORI_OPERATOR_TOKEN}`,'x-request-id':action.idempotency_key},body:JSON.stringify(p)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`R1.1 service rejected operation: ${response.status}`);await client.query(`update operations_action_requests set status='EXECUTED',execution_result=$2,executed_at=now() where id=$1`,[id,result]);await client.query('commit');return {data:{...action,status:'EXECUTED',execution_result:result}}}catch(error){await client.query('rollback');await pool.query(`update operations_action_requests set status='FAILED',execution_result=$2,executed_at=now() where id=$1`,[id,{message:error instanceof Error?error.message:'执行失败'}]);throw error}finally{client.release()}});
app.get('/api/meta/status-labels',async()=>({data:stateCn}));
app.setErrorHandler((error,_req,reply)=>{app.log.error(error);reply.code(500).send({code:'OPERATIONS_ERROR',message:'暂时无法完成操作，请稍后重试'})});
await app.listen({port:env.PORT,host:'0.0.0.0'});
