server { listen 80; server_name wfh_operations.test.shenxinyou.com; return 301 https://$host$request_uri; }
server {
    listen 443 ssl; http2 on; server_name wfh_operations.test.shenxinyou.com;
    ssl_certificate /etc/nginx/ssl/shenxinyou.com/wildcard_bundle.pem;
    ssl_certificate_key /etc/nginx/ssl/shenxinyou.com/wildcard.key;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    location /operations-api/ { proxy_pass http://127.0.0.1:3221/api/; proxy_set_header Host $host; proxy_set_header X-Request-Id $request_id; proxy_set_header X-Forwarded-Proto https; }
    location / { proxy_pass http://127.0.0.1:6920; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto https; }
}
