"use client";
import {useEffect,useState} from 'react';
import {operationsFetch} from './api';
import './development-center.css';
import './development-center-live.css';
import './development-center-spec.css';

type Tab='总览'|'功能与版本'|'研发节奏'|'代码分析'|'测试质量'|'Issue与风险'|'数据健康';
const tabs:Tab[]=['总览','功能与版本','研发节奏','代码分析','测试质量','Issue与风险','数据健康'];
const codes:Record<Tab,string>={'总览':'ADMIN-DEV-01','功能与版本':'ADMIN-DEV-02','研发节奏':'ADMIN-DEV-03','代码分析':'ADMIN-DEV-04','测试质量':'ADMIN-DEV-05','Issue与风险':'ADMIN-DEV-06','数据健康':'ADMIN-DEV-07'};
const show=(value:unknown,suffix='')=>value===null||value===undefined?'尚未接入':`${value}${suffix}`;
export function DevelopmentCenter(){const [tab,setTab]=useState<Tab>('总览'),[release,setRelease]=useState('R1.1'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const load=(selected=release,force=false)=>{setLoading(true);setError('');operationsFetch<{data:any}>(force?'/development-center/refresh':`/development-center?release=${selected}`,force?{method:'POST',body:JSON.stringify({release:selected})}:undefined).then(x=>setData(x.data)).catch(e=>setError(e instanceof Error?e.message:'读取失败')).finally(()=>setLoading(false))};useEffect(load,[]);if(error&&!data)return <DevState title="研发数据读取失败" note={error} retry={load}/>;if(!data)return <DevState title="正在读取研发证据" note="正在读取最近一次成功快照。"/>;const d=data,captured=d.snapshot?.capturedAt||d.source.updatedAt;return <section className="admin-page dev-center"><div className="dev-filter"><label><span>Release</span><select value={release} onChange={e=>{setRelease(e.target.value);load(e.target.value)}}>{d.releases.map((x:string)=><option key={x}>{x}</option>)}</select></label><label><span>阶段</span><select value={d.release.stage} disabled><option>{d.release.stage}</option></select></label><label><span>环境</span><select value={d.release.environment} disabled><option>{d.release.environment}</option></select></label><label><span>标签</span><select value={d.release.tag} disabled><option>{d.release.tag}</option></select></label><div className="dev-updated"><span>数据更新至</span><strong>{new Date(captured).toLocaleString('zh-CN')}</strong><small>每日 23:00 自动更新</small></div><button className="admin-secondary dev-refresh" onClick={()=>load(release,true)} disabled={loading}><i>↻</i>{loading?'刷新中…':'刷新数据'}</button></div>{error&&<div className="dev-warning">最近一次刷新失败，当前保留上次成功结果：{error}</div>}<div className="dev-trust"><b>●　证据状态（来自代码库与流水线）</b>{d.components.map((x:any)=><span key={x.name}>{x.name}<strong>{x.sha}</strong></span>)}<em>{d.source.mode==='PARTIAL'?'⚠ 发现数据源缺口':'● 数据快照完整'}</em></div><div className="admin-tabbar dev-tabs">{tabs.map(x=><button key={x} className={tab===x?'is-active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="dev-section-head"><span>{codes[tab]}</span><b>{d.release.name} · {d.release.stage}</b><small>数据来源：GitHub 快照 / CI 报告 / 部署回执</small></div>{tab==='总览'&&<Overview d={d}/>} {tab==='功能与版本'&&<Features d={d}/>} {tab==='研发节奏'&&<Rhythm d={d}/>} {tab==='代码分析'&&<Code d={d}/>} {tab==='测试质量'&&<Quality d={d}/>} {tab==='Issue与风险'&&<Issues d={d}/>} {tab==='数据健康'&&<Health d={d}/>}</section>}
function DevState({title,note,retry}:{title:string;note:string;retry?:()=>void}){return <section className="admin-page dev-state"><span>研发数据中心</span><h2>{title}</h2><p>{note}</p>{retry&&<button className="admin-primary" onClick={retry}>重新加载</button>}</section>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <article className="admin-panel dev-card"><h2>{title}</h2>{children}</article>}
function Overview({d}:{d:any}){const risk=[['P0 阻塞风险',d.issues.p0,'待处理'],['P1 高风险',d.issues.p1,'重点关注'],['待验证项',d.issues.pendingVerification,'发布前完成'],['失败工作流',d.quality.flaky.length,'需定位'],['数据缺口',d.source.mode==='PARTIAL'?1:0,'查看详情']];return <div className="dev-grid"><div className="dev-wide"><Card title={`发布生命周期（${d.release.name} · ${d.release.stage}）`}><div className="dev-life">{d.lifecycle.map((x:any,i:number)=><div key={x[0]} className={x[2]==='缺失'?'muted':''}><i>{i===4?'↗':'✓'}</i><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]==='事实'?'GitHub / CI 证据':'等待数据源'}</small></div>)}</div></Card></div><Card title="组件变更与交付概览"><div className="dev-table"><table><thead><tr><th>组件</th><th>代码变更（增/删）</th><th>提交</th><th>测试文件占比</th><th>部署状态</th></tr></thead><tbody>{d.components.map((x:any)=><tr key={x.name}><td><b>{x.name}</b><small className="dev-cell-note">{x.sha}</small></td><td>{x.additions===null?<><span>暂不可完整统计</span><small className="dev-cell-note">{x.differenceReason||'差异数据未返回'}</small></>:`+${x.additions} / −${x.deletions}`}</td><td>{x.commitsCapped?'100+':show(x.commits)}</td><td>{show(x.testFileRate,'%')}<small className="dev-cell-note">{show(x.testCases)} / {show(x.sourceFiles)} 个文件</small></td><td><span className="dev-dot"/> {x.deployment}</td></tr>)}</tbody></table></div><small className="dev-footnote">四个组件分别按目录统计；“测试文件占比”不是代码覆盖率。超出 GitHub 接口上限时不展示假零值。</small></Card><Card title="自动发布摘要（基于证据与历史经验）"><div className="dev-insight"><b>事实</b><p>当前版本处于{d.release.stage}，工作流成功率为 {show(d.quality.passRate,'%')}。</p><b className="amber">边界</b><p>{d.source.message}</p><b>建议</b><p>优先处理失败流水线及 P0/P1 Issue，再进入发布门禁。</p></div></Card><div className="dev-wide"><Card title="风险与验证队列"><div className="dev-risk-cards">{risk.map(x=><div key={x[0]}><b>{x[0]}　{x[1]}</b><p>{x[2]}</p><span>查看全部　›</span></div>)}</div></Card></div></div>}
function Features({d}:{d:any}){return <Card title="功能版本证据链"><div className="dev-table"><table><thead><tr><th>功能</th><th>页面编号</th><th>状态</th><th>前端</th><th>后端接口</th><th>测试</th><th>Issue</th></tr></thead><tbody>{d.features.map((x:any)=><tr key={x.name}><td><b>{x.name}</b></td><td>{x.page}</td><td><em>{x.status}</em></td><td>{x.frontend}</td><td>{x.backend}</td><td>{x.tests}</td><td>{x.issues}</td></tr>)}</tbody></table></div></Card>}
function Rhythm({d}:{d:any}){return <div className="dev-two"><Card title="Release 研发时间线"><div className="dev-timeline">{d.timeline.map((x:any,i:number)=><div key={x[0]}><i>{i+1}</i><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div></Card><Card title="周期口径"><p>开始：{d.release.startedAt}（分支创建）</p><p>结束：{d.release.taggedAt||'最终 Tag 尚未创建'}</p><p>总周期：{d.release.duration}</p><div className="dev-note">推算值必须带“推算”标记；缺失历史事件不会显示为 0。</div></Card></div>}
function Code({d}:{d:any}){const peak=Math.max(1,...d.code.hours);return <div className="dev-two"><Card title="四端代码统计"><div className="dev-kpis">{d.components.map((x:any)=><div key={x.name}><span>{x.name}</span><strong>{show(x.commits)}</strong><small>分支最近提交</small><p>{x.additions===null?'等待 GitHub 差异数据':`+${x.additions} / −${x.deletions}`}</p></div>)}</div><div className="dev-file-list">{d.code.files.map((x:any)=><div key={x.filename}><b>{x.filename}</b><span>+{x.additions} / −{x.deletions}</span></div>)}</div></Card><Card title="24 小时提交时钟"><div className="dev-hours">{d.code.hours.map((x:number,i:number)=><div key={i} title={`${i}:00 · ${x} 次`} style={{height:`${18+x/peak*82}%`}}><span>{i%3===0?i:''}</span></div>)}</div><p className="dev-caption">按 Asia/Shanghai 归一化；柱高代表提交次数，不用于个人绩效。</p></Card><Card title="统计排除规则"><div className="dev-chips">{d.code.exclusions.map((x:string)=><span key={x}>{x}</span>)}</div></Card></div>}
function Quality({d}:{d:any}){return <><div className="dev-metrics">{[['测试文件',d.quality.cases,'个'],['功能覆盖率',d.quality.functionCoverage,'%'],['Actions执行率',d.quality.executionRate,'%'],['代码覆盖率',d.quality.codeCoverage,'%'],['工作流成功率',d.quality.passRate,'%']].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{show(x[1],String(x[2]))}</strong><small>{x[1]===null?'报告尚未上传':'GitHub 实时口径'}</small></article>)}</div><Card title="发布门禁与失败工作流"><div className="dev-note">{d.quality.gate}</div>{d.quality.flaky.length?<div className="dev-list">{d.quality.flaky.map((x:any)=><a key={x.url} href={x.url} target="_blank" rel="noreferrer"><b>{x.name}</b><span>{new Date(x.createdAt).toLocaleString('zh-CN')}</span></a>)}</div>:<div className="dev-empty">当前没有读取到失败工作流；逐用例不稳定率需 Actions 上传 JUnit 后计算。</div>}</Card></>}
function Issues({d}:{d:any}){return <><div className="dev-metrics">{[['Issue 总量',d.issues.total],['P0',d.issues.p0],['P1',d.issues.p1],['待验证',d.issues.pendingVerification],['重新打开',d.issues.reopened],['上线逃逸',d.issues.escaped]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{show(x[1])}</strong><small>Release 标签口径</small></article>)}</div><Card title="Issue 聚类与风险"><p>{d.issues.message}</p>{d.issues.groups.length?<div className="dev-table"><table><thead><tr><th>Issue</th><th>模块</th><th>类型</th><th>优先级</th><th>状态</th><th>更新时间</th></tr></thead><tbody>{d.issues.groups.map((x:any)=><tr key={x.number}><td><a href={x.url} target="_blank" rel="noreferrer">#{x.number} {x.title}</a></td><td>{x.module}</td><td>{x.type}</td><td>{x.priority}</td><td>{x.state}</td><td>{new Date(x.updatedAt).toLocaleDateString('zh-CN')}</td></tr>)}</tbody></table></div>:<div className="dev-empty">当前 Release 没有匹配 Issue。</div>}</Card></>}
function Health({d}:{d:any}){return <Card title="研发数据源健康"><div className="dev-health">{d.health.map((x:any)=><div key={x.source}><b>{x.source}</b><em className={x.status==='可用'?'ok':''}>{x.status}</em><span>{x.freshness}</span><p>{x.detail}</p></div>)}</div></Card>}
