"use client";
import {useEffect,useState} from 'react';
import {operationsFetch} from './api';
import './development-center.css';
import './development-center-live.css';

type Tab='总览'|'功能与版本'|'研发节奏'|'代码分析'|'测试质量'|'Issue与风险'|'数据健康';
const tabs:Tab[]=['总览','功能与版本','研发节奏','代码分析','测试质量','Issue与风险','数据健康'];
const codes:Record<Tab,string>={'总览':'ADMIN-DEV-01','功能与版本':'ADMIN-DEV-02','研发节奏':'ADMIN-DEV-03','代码分析':'ADMIN-DEV-04','测试质量':'ADMIN-DEV-05','Issue与风险':'ADMIN-DEV-06','数据健康':'ADMIN-DEV-07'};
const show=(value:unknown,suffix='')=>value===null||value===undefined?'尚未接入':`${value}${suffix}`;
export function DevelopmentCenter(){const [tab,setTab]=useState<Tab>('总览'),[release,setRelease]=useState('R1.1'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const load=(selected=release)=>{setLoading(true);setError('');operationsFetch<{data:any}>(`/development-center?release=${selected}`).then(x=>setData(x.data)).catch(e=>setError(e instanceof Error?e.message:'读取失败')).finally(()=>setLoading(false))};useEffect(load,[]);if(error&&!data)return <DevState title="研发数据读取失败" note={error} retry={load}/>;if(!data)return <DevState title="正在读取研发证据" note="正在核对 Release、部署和数据源状态。"/>;const d=data;return <section className="admin-page dev-center"><div className="dev-filter"><label>Release<select value={release} onChange={e=>{setRelease(e.target.value);load(e.target.value)}}>{d.releases.map((x:string)=><option key={x}>{x}</option>)}</select></label><label>阶段<strong>{d.release.stage}</strong></label><label>环境<strong>{d.release.environment}</strong></label><label>标签<strong>{d.release.tag}</strong></label><span>数据更新至 {new Date(d.source.updatedAt).toLocaleString('zh-CN')}</span><button className="admin-secondary" onClick={()=>load()} disabled={loading}>{loading?'刷新中…':'刷新数据'}</button></div><div className="dev-trust"><b>ⓘ 证据状态</b>{d.components.map((x:any)=><span key={x.name}>{x.name}<strong>{x.sha}</strong></span>)}<em>{d.source.mode==='PARTIAL'?'部分数据源待接入':'数据完整'}</em></div><div className="admin-tabbar dev-tabs">{tabs.map(x=><button key={x} className={tab===x?'is-active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="dev-code">{codes[tab]} · {d.release.name} · {d.release.stage}</div>{tab==='总览'&&<Overview d={d}/>} {tab==='功能与版本'&&<Features d={d}/>} {tab==='研发节奏'&&<Rhythm d={d}/>} {tab==='代码分析'&&<Code d={d}/>} {tab==='测试质量'&&<Quality d={d}/>} {tab==='Issue与风险'&&<Issues d={d}/>} {tab==='数据健康'&&<Health d={d}/>}</section>}
function DevState({title,note,retry}:{title:string;note:string;retry?:()=>void}){return <section className="admin-page dev-state"><span>研发数据中心</span><h2>{title}</h2><p>{note}</p>{retry&&<button className="admin-primary" onClick={retry}>重新加载</button>}</section>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <article className="admin-panel dev-card"><h2>{title}</h2>{children}</article>}
function Overview({d}:{d:any}){return <div className="dev-grid"><Card title={`发布生命周期（${d.release.name} · ${d.release.stage}）`}><div className="dev-life">{d.lifecycle.map((x:any,i:number)=><div key={x[0]} className={x[2]==='缺失'?'muted':''}><i>{i+1}</i><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></Card><Card title="四端变更与交付概览"><table><thead><tr><th>组件</th><th>代码变更</th><th>提交</th><th>测试</th><th>部署</th></tr></thead><tbody>{d.components.map((x:any)=><tr key={x.name}><td><b>{x.name}</b><small>{x.path}</small></td><td>{x.additions===null?'尚未接入':`+${x.additions} / −${x.deletions}`}</td><td>{show(x.commits)}</td><td>{show(x.testRate,'%')}</td><td>{x.deployment}</td></tr>)}</tbody></table></Card><Card title="AI 发布摘要（基于证据与缺口）"><div className="dev-insight"><b>事实</b><p>当前 Release 处于测试中；研发数据页面与受控接口已经开始建设。</p><b>缺口</b><p>{d.source.message}</p><b>建议</b><p>优先安装只读 GitHub App，并让 Actions 上传测试与覆盖率报告。</p></div></Card><Card title="风险与验证队列"><div className="dev-risk"><b>发布门禁</b><span>{d.quality.gate}</span><b>Issue</b><span>{d.issues.message}</span><b>版本漂移</b><span>四端 SHA 尚未接入，当前不能比较。</span></div></Card></div>}
function Features({d}:{d:any}){return <Card title="功能版本证据链"><div className="dev-table"><table><thead><tr><th>功能</th><th>页面编号</th><th>状态</th><th>前端</th><th>后端接口</th><th>测试</th><th>Issue</th></tr></thead><tbody>{d.features.map((x:any)=><tr key={x.name}><td><b>{x.name}</b></td><td>{x.page}</td><td><em>{x.status}</em></td><td>{x.frontend}</td><td>{x.backend}</td><td>{x.tests}</td><td>{x.issues}</td></tr>)}</tbody></table></div></Card>}
function Rhythm({d}:{d:any}){return <div className="dev-two"><Card title="Release 研发时间线"><div className="dev-timeline">{d.timeline.map((x:any,i:number)=><div key={x[0]}><i>{i+1}</i><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div></Card><Card title="周期口径"><p>开始：{d.release.startedAt}（分支创建）</p><p>结束：{d.release.taggedAt||'最终 Tag 尚未创建'}</p><p>总周期：{d.release.duration}</p><div className="dev-note">推算值必须带“推算”标记；缺失历史事件不会显示为 0。</div></Card></div>}
function Code({d}:{d:any}){const peak=Math.max(1,...d.code.hours);return <div className="dev-two"><Card title="四端代码统计"><div className="dev-kpis">{d.components.map((x:any)=><div key={x.name}><span>{x.name}</span><strong>{show(x.commits)}</strong><small>分支最近提交</small><p>{x.additions===null?'等待 GitHub 差异数据':`+${x.additions} / −${x.deletions}`}</p></div>)}</div><div className="dev-file-list">{d.code.files.map((x:any)=><div key={x.filename}><b>{x.filename}</b><span>+{x.additions} / −{x.deletions}</span></div>)}</div></Card><Card title="24 小时提交时钟"><div className="dev-hours">{d.code.hours.map((x:number,i:number)=><div key={i} title={`${i}:00 · ${x} 次`} style={{height:`${18+x/peak*82}%`}}><span>{i%3===0?i:''}</span></div>)}</div><p className="dev-caption">按 Asia/Shanghai 归一化；柱高代表提交次数，不用于个人绩效。</p></Card><Card title="统计排除规则"><div className="dev-chips">{d.code.exclusions.map((x:string)=><span key={x}>{x}</span>)}</div></Card></div>}
function Quality({d}:{d:any}){return <><div className="dev-metrics">{[['测试文件',d.quality.cases,'个'],['功能覆盖率',d.quality.functionCoverage,'%'],['Actions执行率',d.quality.executionRate,'%'],['代码覆盖率',d.quality.codeCoverage,'%'],['工作流成功率',d.quality.passRate,'%']].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{show(x[1],String(x[2]))}</strong><small>{x[1]===null?'报告尚未上传':'GitHub 实时口径'}</small></article>)}</div><Card title="发布门禁与失败工作流"><div className="dev-note">{d.quality.gate}</div>{d.quality.flaky.length?<div className="dev-list">{d.quality.flaky.map((x:any)=><a key={x.url} href={x.url} target="_blank" rel="noreferrer"><b>{x.name}</b><span>{new Date(x.createdAt).toLocaleString('zh-CN')}</span></a>)}</div>:<div className="dev-empty">当前没有读取到失败工作流；逐用例不稳定率需 Actions 上传 JUnit 后计算。</div>}</Card></>}
function Issues({d}:{d:any}){return <><div className="dev-metrics">{[['Issue 总量',d.issues.total],['P0',d.issues.p0],['P1',d.issues.p1],['待验证',d.issues.pendingVerification],['重新打开',d.issues.reopened],['上线逃逸',d.issues.escaped]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{show(x[1])}</strong><small>Release 标签口径</small></article>)}</div><Card title="Issue 聚类与风险"><p>{d.issues.message}</p>{d.issues.groups.length?<div className="dev-table"><table><thead><tr><th>Issue</th><th>模块</th><th>类型</th><th>优先级</th><th>状态</th><th>更新时间</th></tr></thead><tbody>{d.issues.groups.map((x:any)=><tr key={x.number}><td><a href={x.url} target="_blank" rel="noreferrer">#{x.number} {x.title}</a></td><td>{x.module}</td><td>{x.type}</td><td>{x.priority}</td><td>{x.state}</td><td>{new Date(x.updatedAt).toLocaleDateString('zh-CN')}</td></tr>)}</tbody></table></div>:<div className="dev-empty">当前 Release 没有匹配 Issue。</div>}</Card></>}
function Health({d}:{d:any}){return <Card title="研发数据源健康"><div className="dev-health">{d.health.map((x:any)=><div key={x.source}><b>{x.source}</b><em className={x.status==='可用'?'ok':''}>{x.status}</em><span>{x.freshness}</span><p>{x.detail}</p></div>)}</div></Card>}
