"use client";
import { useEffect, useState } from "react";
import "./admin.css";
import {operationsFetch} from './api';
import {OperationsLogin} from './login';

type View="dashboard"|"users"|"benefits"|"products"|"orders"|"approvals"|"system"|"audit";
type User={id?:string;phone:string;name:string;profile:string;member:string;seed:number;status:string};
type Product={id:string;name:string;kind:"单次产品"|"服务包"|"会员计划";price:string;seedPrice:string;version:string;status:string;summary:string;validity:string;delivery:string;contents:string[]};
const nav:[View,string,string][]=[["dashboard","工作台","台"],["users","用户中心","人"],["benefits","权益中心","益"],["products","商品中心","品"],["orders","交易中心","单"],["approvals","审核中心","审"],["audit","操作审计","记"],["system","系统管理","设"]];
const users:User[]=[];
const goods:Product[]=[];
type Order={id:string;user:string;item:string;amount:string;pay:string;grant:string};
const orders:Order[]=[];
type DashboardData={new_users:number;pending_orders:number;open_cases:number;critical_cases:number};
const statusCn:Record<string,string>={ACTIVE:"生效中",INACTIVE:"已停用",DRAFT:"草稿",PUBLISHED:"已上架",RETIRED:"已归档",PENDING_PAYMENT:"待支付",PAYMENT_PROCESSING:"支付确认中",PAID:"支付成功",FULFILLING:"权益到账中",FULFILLED:"已到账",EXCEPTION:"到账异常",OPEN:"待处理",RESOLVED:"已解决"};
const cn=(value:unknown)=>statusCn[String(value)]||String(value||"—");

export default function AdminPage(){
 const [view,setView]=useState<View>("dashboard"),[user,setUser]=useState<User|null>(null),[grant,setGrant]=useState(false),[toast,setToast]=useState("");
 const [auth,setAuth]=useState<"checking"|"ready"|"login">("checking"),[liveUsers,setLiveUsers]=useState<User[]>([]),[liveGoods,setLiveGoods]=useState<Product[]>([]),[liveOrders,setLiveOrders]=useState<Order[]>([]),[dashboard,setDashboard]=useState<DashboardData|null>(null),[loadError,setLoadError]=useState("");
 const load=async()=>{setLoadError("");try{const [u,p,o,d]=await Promise.all([operationsFetch<{data:any[]}>("/users"),operationsFetch<{data:any[]}>("/products"),operationsFetch<{data:any[]}>("/orders"),operationsFetch<{data:DashboardData}>("/dashboard")]);setLiveUsers(u.data.map(x=>({id:x.id,phone:x.phone_masked||"未绑定手机号",name:`用户 ${String(x.id).slice(0,6)}`,profile:"查看详情",member:"查看权益",seed:Number(x.seed_balance||0),status:cn(x.status)})));setLiveGoods(p.data.map(x=>({id:x.code||x.id,name:x.display_name||"未命名商品",kind:x.offering_kind==="MEMBERSHIP"?"会员计划":x.offering_kind==="PACKAGE"?"服务包":"单次产品",price:`¥ ${(Number(x.amount_minor||0)/100).toFixed(2)}`,seedPrice:x.reserved_seed_quantity?`${x.minimum_seed_balance||0} 颗解锁 ¥ ${(Number(x.activity_amount_minor||0)/100).toFixed(2)}`:"未配置",version:`V${x.version||1}`,status:cn(x.status),summary:x.description||"暂无用户端说明",validity:x.validity_days?`购买后 ${x.validity_days} 天`:"按商品规则",delivery:"购买成功后生效",contents:Object.entries(x.entitlement_spec||{}).map(([k,v])=>`${k} × ${v}`)})));setLiveOrders(o.data.map(x=>({id:x.order_number||x.id,user:`用户 ${String(x.owner_user_id).slice(0,6)}`,item:x.display_name||"未命名商品",amount:`¥ ${(Number(x.amount_minor||0)/100).toFixed(2)}`,pay:cn(x.status),grant:cn(x.fulfillment_status)})));setDashboard(d.data);setAuth("ready")}catch(e){if(String(e).includes("登录")||String(e).includes("401")){localStorage.removeItem("fresh_operations_token");setAuth("login")}else{setLoadError(e instanceof Error?e.message:"数据加载失败");setAuth("ready")}}};
 useEffect(()=>{if(localStorage.getItem("fresh_operations_token"))void load();else setAuth("login")},[]);
 if(auth==="checking")return <main className="operations-login"><p>正在验证运营账号…</p></main>;
 if(auth==="login")return <OperationsLogin done={()=>{setAuth("checking");void load()}}/>;
 const go=(v:View)=>{setView(v);setUser(null)}; const tell=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),2200)};
 const title={dashboard:"工作台",users:"用户中心",benefits:"权益中心",products:"商品中心",orders:"交易中心",approvals:"审核中心",system:"系统管理",audit:"操作审计"}[view];
 return <main className="admin-shell">
  <aside className="admin-sidebar"><div className="admin-brand"><span className="admin-brand-mark">初</span><div><strong>初见 · FRESH</strong><small>运营管理平台</small></div></div><nav>{nav.map(([id,label,icon])=><button className={view===id?"is-active":""} onClick={()=>go(id)} key={id}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="admin-account"><span>F</span><div><strong>Fred</strong><small>产品运营 · 用户运营</small></div></div></aside>
  <section className="admin-main"><header className="admin-topbar"><div><p>{({dashboard:"ADMIN-HOME-01",users:"ADMIN-USER-01",benefits:"ADMIN-BENEFIT-01",products:"ADMIN-PRODUCT-01",orders:"ADMIN-ORDER-01",approvals:"ADMIN-APPROVAL-01",system:"ADMIN-SYSTEM-01",audit:"ADMIN-AUDIT-01"})[view]} · 运营平台原型</p><h1>{title}</h1></div><div className="admin-top-actions"><button className="admin-secondary" onClick={()=>go("audit")}>操作记录</button><button className="admin-primary" onClick={()=>setGrant(true)}>＋ 人工发放</button></div></header>
   {loadError&&<div className="risk-note">真实数据加载失败：{loadError} <button onClick={()=>void load()}>重试</button></div>}
   {view==="dashboard"&&<Dashboard go={go} data={dashboard}/>} {view==="users"&&<Users data={liveUsers} reload={load} open={setUser}/>} {view==="benefits"&&<Benefits tell={tell}/>} {view==="products"&&<Products data={liveGoods} tell={tell}/>} {view==="orders"&&<Orders data={liveOrders} tell={tell}/>} {view==="approvals"&&<Approvals tell={tell}/>} {view==="system"&&<System tell={tell}/>} {view==="audit"&&<Audit/>}
  </section>
  {user&&<UserPanel user={user} close={()=>setUser(null)} grant={()=>setGrant(true)}/>} {grant&&<Grant close={()=>setGrant(false)} done={()=>{setGrant(false);tell("发放申请已保存，等待审核")}}/>} {toast&&<div className="admin-toast">✓ {toast}</div>}
 </main>
}

function Dashboard({go,data}:{go:(v:View)=>void;data:DashboardData|null}){const stats=[["今日新增用户",String(data?.new_users??"—"),"来自 R1.1 用户数据"],["待处理对账",String(data?.open_cases??"—"),"需要运营核对"],["严重到账异常",String(data?.critical_cases??"—"),"优先处理"],["待支付订单",String(data?.pending_orders??"—"),"来自真实订单"]];return <><section className="admin-stat-grid">{stats.map(s=><article className="admin-stat" key={s[0]}><p>{s[0]}</p><strong>{s[1]}</strong><small>{s[2]}</small></article>)}</section><section className="admin-grid"><article className="admin-panel"><Head en="TODAY" title="今日待处理"/><Task tone="danger" title={`${data?.critical_cases??0} 笔严重到账异常`} note="优先核对支付回调与权益发放流水" action="立即处理" click={()=>go("orders")}/><Task tone="warning" title={`${data?.open_cases??0} 条对账事项待处理`} note="处理结果将写入操作审计" action="查看事项" click={()=>go("benefits")}/><Task tone="info" title="商品配置按版本管理" note="修改先保存草稿，经审核后发布" action="商品中心" click={()=>go("products")}/></article><article className="admin-panel"><Head en="QUICK ACCESS" title="常用操作"/><div className="admin-quick-grid"><button onClick={()=>go("users")}><b>查</b><span>查询用户</span></button><button onClick={()=>go("benefits")}><b>赠</b><span>权益流水</span></button><button onClick={()=>go("products")}><b>品</b><span>配置产品</span></button><button onClick={()=>go("orders")}><b>单</b><span>诊断订单</span></button></div></article></section></>}
function Users({data,reload,open}:{data:User[];reload:()=>Promise<void>;open:(u:User)=>void}){const [query,setQuery]=useState(""),[result,setResult]=useState<User[]>(data),[loading,setLoading]=useState(false);useEffect(()=>setResult(data),[data]);const search=async()=>{setLoading(true);try{const response=await operationsFetch<{data:any[]}>(`/users?q=${encodeURIComponent(query)}`);setResult(response.data.map(x=>({id:x.id,phone:x.phone_masked||"未绑定手机号",name:`用户 ${String(x.id).slice(0,6)}`,profile:"查看详情",member:"查看权益",seed:Number(x.seed_balance||0),status:cn(x.status)})))}finally{setLoading(false)}};return <section className="admin-page"><div className="admin-toolbar"><label className="admin-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入手机号、用户编号或昵称" onKeyDown={e=>e.key==="Enter"&&void search()}/></label><button className="admin-primary" onClick={()=>void search()} disabled={loading}>{loading?"查询中…":"查询用户"}</button><button className="admin-secondary" onClick={()=>{setQuery("");void reload()}}>重置</button><span className="admin-hint">默认隐藏敏感信息，完整手机号仅在授权后显示</span></div><article className="admin-panel admin-table-panel"><Head en="USER LIST" title={`用户列表 · ${result.length} 人`}/>{result.length?<><table><thead><tr><th>用户</th><th>档案</th><th>会员</th><th>智慧种子</th><th>状态</th><th/></tr></thead><tbody>{result.map(u=><tr key={u.id||u.phone}><td><b>{u.name}</b><small>{u.phone}</small></td><td>{u.profile}</td><td>{u.member}</td><td>{u.seed} 颗</td><td><Tag value={u.status}/></td><td><button className="admin-link" onClick={()=>open(u)}>查看详情 →</button></td></tr>)}</tbody></table><Pagination/></>:<div className="empty-state"><b>没有找到匹配用户</b><span>请检查手机号或用户编号。</span></div>}</article></section>}
function Benefits({tell}:{tell:(s:string)=>void}){const [tab,setTab]=useState("智慧种子"),[data,setData]=useState<any[]>([]),[error,setError]=useState("");const tabs=["智慧种子","服务权益","待领取权益"];useEffect(()=>{operationsFetch<{data:any[]}>("/benefits").then(x=>setData(x.data)).catch(e=>setError(e.message))},[]);const filtered=data.filter(x=>tab==="待领取权益"?x.status==="PENDING_CLAIM":x.kind===tab);return <section className="admin-page"><div className="admin-tabbar">{tabs.map(x=><button className={tab===x?"is-active":""} onClick={()=>setTab(x)} key={x}>{x}<b>{x==="待领取权益"?data.filter(y=>y.status==="PENDING_CLAIM").length:data.filter(y=>y.kind===x).length}</b></button>)}</div>{error&&<div className="risk-note">{error}</div>}<article className="admin-panel admin-table-panel"><Head en="BENEFIT LEDGER" title={`${tab} · 真实权益记录`}/>{filtered.length?<table><thead><tr><th>记录编号</th><th>用户</th><th>总量</th><th>可用</th><th>到期时间</th><th>状态</th><th/></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{String(x.id).slice(0,8)}</b></td><td>{String(x.owner_user_id).slice(0,8)}</td><td>{x.total_quantity}</td><td>{x.available_quantity}</td><td>{x.expires_at?new Date(x.expires_at).toLocaleDateString("zh-CN"):"长期"}</td><td><Tag value={cn(x.status)}/></td><td><button className="admin-link" onClick={()=>tell(`权益记录 ${x.id}`)}>查看 →</button></td></tr>)}</tbody></table>:<div className="empty-state"><b>暂无记录</b><span>这里不会使用示例数据填充。</span></div>}</article></section>}
function SeedLedger(){return <><section className="admin-stat-grid compact"><Stat a="今日发放" b="1,280" c="42 位用户"/><Stat a="今日使用" b="386" c="含 27 笔预占"/><Stat a="异常流水" b="2" c="等待人工复核"/></section><article className="admin-panel admin-table-panel"><Head en="SEED LEDGER" title="最近智慧种子流水"/><table><thead><tr><th>时间</th><th>用户</th><th>变化</th><th>余额</th><th>来源</th><th>业务单据</th><th>结果</th></tr></thead><tbody><tr><td>10:31</td><td>林知夏</td><td className="positive">+18</td><td>18</td><td>新用户启程礼</td><td>GR20260902031</td><td><Tag value="已到账"/></td></tr><tr><td>10:18</td><td>许遥</td><td>-80</td><td>80</td><td>清和计划解锁价</td><td>FR202609020017</td><td><Tag value="已预占"/></td></tr><tr><td>09:46</td><td>周予安</td><td className="positive">+18</td><td>0</td><td>客服异常补偿</td><td>GR20260902024</td><td><Tag value="待领取"/></td></tr></tbody></table><Pagination/></article></>}
function MembershipRights({tell}:{tell:(s:string)=>void}){return <article className="admin-panel admin-table-panel benefit-table"><Head en="MEMBERSHIP" title="用户会员权益"/><table><thead><tr><th>用户</th><th>会员计划</th><th>生效时间</th><th>到期时间</th><th>权益刷新</th><th>状态</th><th/></tr></thead><tbody><tr><td>林知夏</td><td>清和计划 V4</td><td>2026-09-01</td><td>2026-10-01</td><td>每周期一次</td><td><Tag value="生效中"/></td><td><button className="admin-link" onClick={()=>tell("已打开会员详情")}>查看 →</button></td></tr><tr><td>许遥</td><td>微光计划 V2</td><td>2026-08-18</td><td>2026-09-17</td><td>不结转</td><td><Tag value="生效中"/></td><td><button className="admin-link">查看 →</button></td></tr></tbody></table></article>}
function PackageRights({tell}:{tell:(s:string)=>void}){return <article className="admin-panel admin-table-panel benefit-table"><Head en="SERVICE PACKAGE" title="服务包与剩余次数"/><table><thead><tr><th>用户</th><th>服务包</th><th>剩余/总次数</th><th>最近核销</th><th>到期时间</th><th>状态</th><th/></tr></thead><tbody><tr><td>林知夏</td><td>抽卡问事 · 10 次包 V2</td><td><b>8 / 10 次</b></td><td>09-01 21:42</td><td>2027-02-28</td><td><Tag value="可使用"/></td><td><button className="admin-link" onClick={()=>tell("已打开核销记录")}>核销记录 →</button></td></tr><tr><td>周予安</td><td>关系疗愈 · 3 次包 V1</td><td><b>0 / 3 次</b></td><td>08-22 16:20</td><td>2026-09-22</td><td><Tag value="已用完"/></td><td><button className="admin-link">核销记录 →</button></td></tr></tbody></table></article>}
function PendingRights({tell}:{tell:(s:string)=>void}){return <article className="admin-panel admin-table-panel benefit-table"><Head en="PENDING CLAIM" title="待领取权益"/><table><thead><tr><th>手机号</th><th>权益内容</th><th>生效条件</th><th>创建来源</th><th>到期时间</th><th>状态</th><th/></tr></thead><tbody><tr><td><b>186****9401</b><small>尚未完成领取</small></td><td>18 颗智慧种子</td><td>手机号登录后</td><td>客服异常补偿</td><td>2026-09-30</td><td><Tag value="待领取"/></td><td><button className="admin-link" onClick={()=>tell("已重新发送领取提醒")}>提醒领取</button></td></tr><tr><td>139****2016</td><td>清和计划 30 天</td><td>首次注册后</td><td>线下活动赠送</td><td>2026-10-15</td><td><Tag value="待领取"/></td><td><button className="admin-link">查看 →</button></td></tr></tbody></table><div className="batch-bar"><span>已选择 0 条</span><button disabled>批量延长有效期</button><button disabled>批量撤销</button></div></article>}
function Products({data,tell}:{data:Product[];tell:(s:string)=>void}){
 const filters=["全部商品","单次产品","服务包","会员计划"] as const; const [filter,setFilter]=useState<(typeof filters)[number]>("全部商品"),[selected,setSelected]=useState<Product|null>(null),[creating,setCreating]=useState(false);
 const rows=filter==="全部商品"?data:data.filter(g=>g.kind===filter);
 return <section className="admin-page"><div className="admin-tabbar">{filters.map(f=><button key={f} className={filter===f?"is-active":""} onClick={()=>setFilter(f)}>{f} <b>{f==="全部商品"?data.length:data.filter(g=>g.kind===f).length}</b></button>)}<span/><button className="admin-primary" onClick={()=>setCreating(true)}>＋ 新建商品</button></div>
  <div className="product-summary"><div><strong>{rows.length}</strong><span>当前分类商品</span></div><div><strong>{rows.filter(x=>x.status==="已上架").length}</strong><span>已上架</span></div><div><strong>{rows.filter(x=>x.status==="待审核").length}</strong><span>待审核</span></div><p>商品价格、权益和有效期均按版本发布；修改不会影响历史订单。</p></div>
  <article className="admin-panel admin-table-panel"><Head en="PRODUCT CATALOG" title={`${filter} · 商品与版本`}/><table><thead><tr><th>商品</th><th>类型</th><th>标准价格</th><th>种子解锁</th><th>有效期</th><th>版本</th><th>状态</th><th/></tr></thead><tbody>{rows.map(g=><tr key={g.id}><td><b>{g.name}</b><small>{g.id}</small></td><td>{g.kind}</td><td>{g.price}</td><td>{g.seedPrice}</td><td>{g.validity}</td><td>{g.version}</td><td><Tag value={g.status}/></td><td><button className="admin-link" onClick={()=>setSelected(g)}>查看并配置 →</button></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty-state"><b>当前分类暂无商品</b><span>可以新建草稿，完成校验和审核后再发布。</span></div>}<div className="admin-version-note"><b>版本发布原则</b><span>草稿 → 校验 → 审核 → 用户端预览 → 发布。已发布版本不可覆盖，历史订单读取购买时快照。</span></div></article>
  {selected&&<ProductEditor product={selected} close={()=>setSelected(null)} tell={tell}/>} {creating&&<NewProduct close={()=>setCreating(false)} next={(kind)=>{setCreating(false);setSelected(data.find(g=>g.kind===kind)||null);tell("请在后端商品中心创建草稿版本")}}/>}
 </section>
}
function ProductEditor({product,close,tell}:{product:Product;close:()=>void;tell:(s:string)=>void}){
 const [section,setSection]=useState("基础信息"),[preview,setPreview]=useState(false); const sections=["基础信息",product.kind==="单次产品"?"交付规则":product.kind==="服务包"?"服务组合":"会员权益","价格与种子","版本记录"];
 return <div className="admin-overlay" onClick={close}><aside className="admin-product-drawer" onClick={e=>e.stopPropagation()}><header className="product-editor-head"><div><button className="back-link" onClick={close}>← 返回商品列表</button><p className="admin-eyebrow">{product.id} · {product.version}</p><h2>{product.name}</h2><div className="product-meta"><Tag value={product.kind}/><Tag value={product.status}/><span>最后更新：今天 10:18</span></div></div><div><button className="admin-secondary" onClick={()=>setPreview(!preview)}>{preview?"返回配置":"用户端预览"}</button><button className="admin-primary" onClick={()=>tell(product.status==="待审核"?"审核详情已打开":"已复制为新草稿版本")}>{product.status==="待审核"?"查看审核":"复制新版本"}</button></div></header>
   {preview?<ProductPreview product={product}/>:<div className="product-editor-body"><nav className="editor-sections">{sections.map(x=><button key={x} className={section===x?"is-active":""} onClick={()=>setSection(x)}>{x}</button>)}</nav><section className="editor-form"><h3>{section}</h3><p className="section-help">{section==="版本记录"?"已发布版本不可直接修改，每次变更都保留差异、操作者和发布时间。":"以下为当前版本的真实业务配置，保存草稿不会影响用户端。"}</p>{section==="基础信息"&&<><div className="form-grid"><Field label="商品编号" value={product.id} disabled/><Field label="商品类型" value={product.kind} disabled/><Field label="用户端名称" value={product.name}/><Field label="当前状态" value={product.status}/></div><label className="wide-field">用户端说明<textarea defaultValue={product.summary}/></label><div className="form-grid"><Field label="有效期规则" value={product.validity}/><Field label="权益生效" value={product.delivery}/><Field label="是否需要生命智慧档案" value={product.kind==="单次产品"?"需要":"使用相关服务时再判断"}/><Field label="退款规则" value="未使用权益支持申请退款"/></div></>}{section==="交付规则"&&<Delivery product={product}/>} {section==="服务组合"&&<Bundle product={product}/>} {section==="会员权益"&&<Bundle product={product}/>} {section==="价格与种子"&&<Pricing product={product}/>} {section==="版本记录"&&<Versions product={product}/>}<footer className="editor-actions"><span>自动保存于 10:32</span><button className="admin-secondary" onClick={()=>tell("草稿已保存")}>保存草稿</button><button className="admin-primary" onClick={()=>tell("配置校验通过，已提交审核")}>校验并提交审核</button></footer></section></div>}
  </aside></div>
}
function ProductPreview({product}:{product:Product}){return <div className="preview-stage"><div className="preview-phone"><p className="preview-brand">初见 · FRESH</p><small>{product.kind}</small><h3>{product.name}</h3><p>{product.summary}</p><div className="preview-price"><b>{product.price}</b><span>{product.seedPrice}</span></div><ul>{product.contents.map(x=><li key={x}>✓ {x}</li>)}</ul><div className="preview-note">有效期：{product.validity}<br/>权益将在{product.delivery}</div><button>确认购买</button></div><aside><p className="admin-eyebrow">PREVIEW CHECK</p><h3>发布前预览</h3><ul><li>名称与说明是否面向用户表达</li><li>价格和种子条件是否清晰</li><li>权益次数与有效期是否一致</li><li>不展示内部版本号与状态枚举</li></ul></aside></div>}
function Delivery({product}:{product:Product}){return <><div className="config-card"><b>交付内容</b><p>{product.contents[0]}</p><span>完成支付或权益核销后即时发放</span></div><div className="form-grid"><Field label="使用次数" value="1 次"/><Field label="核销方式" value="用户发起服务时自动核销"/><Field label="失败处理" value="权益不扣减，可安全重试"/><Field label="记录保留" value="长期保留在用户问事记录"/></div></>}
function Bundle({product}:{product:Product}){return <><div className="bundle-list">{product.contents.map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b><label>发放方式<select defaultValue={i===0?"一次性发放":"随会员生效"}><option>一次性发放</option><option>随会员生效</option><option>每周期刷新</option></select></label><button>移除</button></div>)}</div><button className="admin-secondary">＋ 添加单次产品或服务包</button><div className="risk-note">组合发布后会生成权益快照。组成项未来修改，不会反向影响已购买用户。</div></>}
function Pricing({product}:{product:Product}){return <><div className="form-grid"><Field label="标准售价" value={product.price.replace("¥ ","")} suffix="元"/><Field label="会员专属价" value={product.kind==="会员计划"?"不适用":"5.90"} suffix="元"/><Field label="活动价格" value="未启用"/><Field label="价格生效时间" value="发布后立即生效"/></div><h4>智慧种子解锁价格</h4><div className="seed-rule"><label><input type="checkbox" defaultChecked/> 启用智慧种子解锁价</label><Field label="所需智慧种子" value={product.kind==="会员计划"?"160":"80"} suffix="颗"/><Field label="解锁后价格" value={product.kind==="会员计划"?"179.00":"49.90"} suffix="元"/><Field label="种子处理方式" value="支付前预占，成功后扣除"/></div><div className="quote-example"><b>报价模拟</b><span>普通用户：{product.price}</span><span>满足种子条件：{product.seedPrice}</span><button>更换模拟用户</button></div></>}
function Versions({product}:{product:Product}){return <div className="version-list"><div><Tag value={product.status}/><b>{product.version} · 当前版本</b><span>Fred · 今天 10:18</span><button>查看差异</button></div><div><Tag value="已归档"/><b>V2 · 上一个版本</b><span>jiucongtian · 8 月 30 日 18:42</span><button>查看快照</button></div><div><Tag value="已归档"/><b>V1 · 首次发布</b><span>Fred · 8 月 26 日 11:05</span><button>查看快照</button></div></div>}
function NewProduct({close,next}:{close:()=>void;next:(k:Product["kind"])=>void}){return <div className="admin-overlay"><section className="admin-modal product-choice"><button className="admin-close" onClick={close}>×</button><p className="admin-eyebrow">NEW PRODUCT</p><h2>选择商品类型</h2><p>类型决定后续配置结构，创建后不可更改。</p><div>{(["单次产品","服务包","会员计划"] as Product["kind"][]).map((x,i)=><button key={x} onClick={()=>next(x)}><b>{["单","包","会"][i]}</b><span><strong>{x}</strong><small>{["独立交付、独立定价和核销","组合一个或多个单次产品","按周期整合产品、服务包和资格"][i]}</small></span><i>→</i></button>)}</div></section></div>}
function Field({label,value,disabled,suffix}:{label:string;value:string;disabled?:boolean;suffix?:string}){return <label className="config-field">{label}<span><input defaultValue={value} disabled={disabled}/>{suffix&&<i>{suffix}</i>}</span></label>}
function Orders({data,tell}:{data:Order[];tell:(s:string)=>void}){const [status,setStatus]=useState("全部状态"),[selected,setSelected]=useState<Order|null>(null);const rows=status==="全部状态"?data:data.filter(o=>o.grant===status||o.pay===status);return <section className="admin-page"><div className="admin-toolbar"><label className="admin-search">⌕<input placeholder="输入订单号、手机号或请求编号"/></label><button className="admin-primary">查询订单</button><select value={status} onChange={e=>setStatus(e.target.value)}><option>全部状态</option><option>待支付</option><option>到账异常</option><option>已到账</option></select></div><article className="admin-panel admin-table-panel"><Head en="ORDER & DELIVERY" title={`订单与权益到账 · ${rows.length} 笔`}/>{rows.length?<><table><thead><tr><th>订单</th><th>用户</th><th>商品</th><th>金额</th><th>支付</th><th>权益</th><th/></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><b>{o.id}</b></td><td>{o.user}</td><td>{o.item}</td><td>{o.amount}</td><td>{o.pay}</td><td><Tag value={o.grant}/></td><td><button className="admin-link" onClick={()=>setSelected(o)}>诊断 →</button></td></tr>)}</tbody></table><Pagination/></>:<div className="empty-state"><b>暂无订单</b><span>这里仅展示 R1.1 数据库中的真实订单。</span></div>}</article>{selected&&<OrderDiagnostic order={selected} close={()=>setSelected(null)} tell={tell}/>}</section>}
function OrderDiagnostic({order,close,tell}:{order:typeof orders[0];close:()=>void;tell:(s:string)=>void}){const abnormal=order.grant==="到账异常";return <div className="admin-overlay" onClick={close}><aside className="admin-drawer order-drawer" onClick={e=>e.stopPropagation()}><button className="admin-close" onClick={close}>×</button><p className="admin-eyebrow">ORDER DIAGNOSTIC</p><h2>订单诊断</h2><p className="drawer-phone">{order.id}</p><div className="order-overview"><Info a="用户" b={order.user}/><Info a="商品" b={order.item}/><Info a="实付" b={order.amount}/><Info a="当前结果" b={order.grant}/></div><h3>交易与交付链路</h3><div className="diagnostic-steps"><Step title="创建订单" time="10:21:03" state="已完成" note="商品与价格版本快照已保存"/><Step title="确认报价" time="10:21:04" state="已完成" note="标准价 ¥199.00，未使用智慧种子"/><Step title="微信支付" time="10:21:28" state={order.pay} note="支付回调已通过签名与金额校验"/><Step title="权益到账" time="10:21:29" state={abnormal?"失败":"已完成"} note={abnormal?"会员权益写入超时，未发现重复发放":"权益账户已更新"}/></div>{abnormal&&<div className="diagnosis"><b>建议处理</b><p>支付已成功，权益尚未到账。系统已确认不存在相同权益和执行中的发放任务，可以发起一次幂等补发。</p><small>内部错误码：ENTITLEMENT_GRANT_TIMEOUT · 请求 01a055dd…</small></div>}<div className="drawer-actions"><button className="admin-secondary" onClick={()=>tell("已复制订单诊断信息")}>复制诊断信息</button><button className="admin-secondary">发起退款</button><button className="admin-primary" disabled={!abnormal} onClick={()=>tell("安全补发申请已提交审核")}>安全补发</button></div></aside></div>}
function Step({title,time,state,note}:{title:string;time:string;state:string;note:string}){return <div className={state==="失败"?"failed":""}><i>{state==="失败"?"!":"✓"}</i><section><b>{title}</b><p>{note}</p><small>{time} · {state}</small></section></div>}
function UserPanel({user,close,grant}:{user:User;close:()=>void;grant:()=>void}){const [tab,setTab]=useState("概览");return <div className="admin-overlay" onClick={close}><aside className="admin-drawer user-drawer" onClick={e=>e.stopPropagation()}><button className="admin-close" onClick={close}>×</button><p className="admin-eyebrow">USER PROFILE · ADMIN-USER-02</p><h2>{user.name}</h2><p className="drawer-phone">{user.phone} · 用户编号 U20260828031</p><div className="drawer-summary"><Info a="档案状态" b={user.profile}/><Info a="智慧种子" b={`${user.seed} 颗`}/><Info a="会员计划" b={user.member}/><Info a="账号状态" b={user.status}/></div><div className="mini-tabs">{["概览","权益","订单","服务记录","客服记录"].map(x=><button className={tab===x?"is-active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="概览"&&<><h3>最近状态</h3><ul className="timeline"><li><b>今日能量生成成功</b><span>今天 08:12</span></li><li><b>会员权益完成刷新</b><span>9 月 1 日 00:03</span></li><li><b>完成生命智慧档案</b><span>8 月 28 日 19:45</span></li></ul></>}{tab==="权益"&&<DetailList items={[["智慧种子",`${user.seed} 颗 · 正常`],["会员",`${user.member} · 2026-10-01 到期`],["服务包","抽卡问事 8/10 次"]]}/>} {tab==="订单"&&<DetailList items={[["FR202609020018","清和计划 · ¥199.00 · 支付成功"],["FR202608280075","抽卡问事 · 1 次权益 · 已完成"]]}/>} {tab==="服务记录"&&<DetailList items={[["今日能量","今天 08:12 · 生成成功"],["抽卡问事","9 月 1 日 21:42 · 报告已完成"]]}/>} {tab==="客服记录"&&<DetailList items={[["权益不到账咨询","9 月 1 日 · 已解决"],["注册启程礼补发","8 月 28 日 · 操作人 Fred"]]}/>}<button className="admin-primary full" onClick={grant}>为该用户发放权益</button></aside></div>}
function DetailList({items}:{items:string[][]}){return <div className="detail-list">{items.map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><button>查看</button></div>)}</div>}
function Grant({close,done}:{close:()=>void;done:()=>void}){const [kind,setKind]=useState("智慧种子"),[phone,setPhone]=useState("13113011314");const unregistered=phone==="13900002016";return <div className="admin-overlay"><section className="admin-modal grant-modal"><button className="admin-close" onClick={close}>×</button><p className="admin-eyebrow">MANUAL GRANT · ADMIN-BENEFIT-05</p><h2>人工发放</h2><label>用户手机号<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="输入完整手机号"/></label><label>发放类型<select value={kind} onChange={e=>setKind(e.target.value)}><option>智慧种子</option><option>会员计划</option><option>服务包</option><option>单次产品</option></select></label>{kind==="智慧种子"&&<div className="form-row"><label>发放数量<input defaultValue="18"/><small>单位：颗</small></label><label>有效期<select><option>长期有效</option><option>30 天</option><option>90 天</option></select></label></div>}{kind==="会员计划"&&<><label>会员计划<select><option>清和计划 V4</option><option>微光计划 V2</option><option>自在计划 V1</option></select></label><div className="form-row"><label>期限<select><option>固定 30 天</option><option>90 天</option><option>180 天</option></select></label><label>生效方式<select><option>立即生效</option><option>首次登录后生效</option><option>指定日期生效</option></select></label></div></>}{kind==="服务包"&&<><label>服务包<select><option>抽卡问事 · 10 次包 V2</option><option>关系疗愈 · 3 次包 V1</option></select></label><div className="form-row"><label>数量<input defaultValue="1"/><small>单位：份</small></label><label>有效期<select><option>购买规则：180 天</option><option>指定日期</option></select></label></div></>}{kind==="单次产品"&&<><label>单次产品<select><option>抽卡问事 V3</option><option>今日能量指引 V2</option></select></label><div className="form-row"><label>次数<input defaultValue="1"/></label><label>核销方式<select><option>用户发起时自动核销</option><option>人工核销</option></select></label></div></>}<label>发放原因<textarea defaultValue="新用户启程礼未正常到账，人工补发。"/></label>{unregistered?<div className="risk-note">该手机号尚未注册。本次权益将进入“待领取权益”，用户通过该手机号注册或登录后自动领取。</div>:<div className="success-note">已找到用户：林知夏。提交后将生成权益流水和操作审计记录。</div>}<label className="confirm-check"><input type="checkbox" defaultChecked/> 我已核对用户、发放内容、数量和有效期</label><div className="modal-actions"><button className="admin-secondary" onClick={close}>保存草稿</button><button className="admin-primary" onClick={done}>{kind==="智慧种子"?"提交审核":"确认并提交审核"}</button></div></section></div>}
function Approvals({tell}:{tell:(s:string)=>void}){const [data,setData]=useState<any[]>([]),[busy,setBusy]=useState("");const load=()=>operationsFetch<{data:any[]}>("/action-requests").then(x=>setData(x.data));useEffect(()=>{void load()},[]);const review=async(id:string,decision:"approve"|"reject")=>{setBusy(id);try{await operationsFetch(`/action-requests/${id}/${decision}`,{method:"POST",body:JSON.stringify({note:decision==="approve"?"核对无误，同意执行":"资料不足，暂不执行"})});tell(decision==="approve"?"审核通过并已执行":"申请已驳回");await load()}catch(e){tell(e instanceof Error?e.message:"审核失败")}finally{setBusy("")}};return <section className="admin-page"><article className="admin-panel admin-table-panel"><Head en="APPROVAL CENTER" title={`审核申请 · ${data.length}`}/>{data.length?<table><thead><tr><th>申请内容</th><th>原因</th><th>提交人</th><th>提交时间</th><th>状态</th><th/></tr></thead><tbody>{data.map(x=><tr key={x.id}><td><b>{cn(x.action_type)}</b><small>{String(x.id).slice(0,8)}</small></td><td>{x.reason}</td><td>{x.submitted_by}</td><td>{new Date(x.created_at).toLocaleString("zh-CN")}</td><td><Tag value={cn(x.status)}/></td><td>{x.status==="PENDING"&&<><button disabled={busy===x.id} className="admin-link" onClick={()=>void review(x.id,"approve")}>通过并执行</button> <button disabled={busy===x.id} className="admin-link" onClick={()=>void review(x.id,"reject")}>驳回</button></>}</td></tr>)}</tbody></table>:<div className="empty-state"><b>暂无审核申请</b><span>人工权益调整和商品变更会在这里留下审批记录。</span></div>}</article></section>}
function System({tell}:{tell:(s:string)=>void}){const [tab,setTab]=useState("账号与角色");return <section className="admin-page"><div className="admin-tabbar">{["账号与角色","权限矩阵","品牌配置","配置发布"].map(x=><button className={tab===x?"is-active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="账号与角色"&&<article className="admin-panel admin-table-panel"><div className="panel-title-action"><Head en="ACCOUNT & ROLE" title="后台账号与角色"/><button className="admin-primary" onClick={()=>tell("邀请账号表单已打开")}>＋ 邀请账号</button></div><table><thead><tr><th>账号</th><th>已分配角色</th><th>数据范围</th><th>有效期</th><th>状态</th><th/></tr></thead><tbody><tr><td><b>Fred</b><small>fred***@outlook.com</small></td><td><span className="role-chip">产品运营</span><span className="role-chip">用户运营</span></td><td>全部产品、全部用户</td><td>长期</td><td><Tag value="正常"/></td><td><button className="admin-link" onClick={()=>tell("可为一个账号勾选多个角色")}>分配角色 →</button></td></tr><tr><td><b>小青</b><small>qing***@shenxinyou.com</small></td><td><span className="role-chip">客服</span></td><td>本人负责的工单</td><td>2026-12-31</td><td><Tag value="正常"/></td><td><button className="admin-link">分配角色 →</button></td></tr><tr><td><b>九重天</b><small>jiu***@shenxinyou.com</small></td><td><span className="role-chip">技术管理员</span><span className="role-chip">超级管理员</span></td><td>系统配置</td><td>长期</td><td><Tag value="正常"/></td><td><button className="admin-link">分配角色 →</button></td></tr></tbody></table></article>}{tab==="权限矩阵"&&<PermissionMatrix/>}{tab==="品牌配置"&&<Placeholder title="品牌配置" text="Logo、品牌色、分享图、客服二维码与官媒二维码在此形成可预览、可发布的配置版本。"/>}{tab==="配置发布"&&<Placeholder title="配置发布" text="展示草稿、测试预览、灰度、正式发布和回退；生产配置不允许直接覆盖。"/>}</section>}
function PermissionMatrix(){const roles=["超级管理员","产品运营","用户运营","客服","财务","内容运营","导师运营","品牌运营","技术管理员","审计人员"];return <article className="admin-panel permission-panel"><Head en="RBAC + DATA SCOPE" title="角色权限矩阵"/><div className="permission-grid"><b>角色</b><b>用户</b><b>商品</b><b>权益</b><b>订单</b><b>发布</b>{roles.map((r,i)=><div className="permission-row" key={r}><strong>{r}</strong><span>{i===0||[2,3].includes(i)?"读写":"只读"}</span><span>{i===0||i===1?"读写":"—"}</span><span>{i<4?"读写":"只读"}</span><span>{i===0||[3,4].includes(i)?"读写":"只读"}</span><span>{i===0?"正式发布":i===1?"提交审核":"—"}</span></div>)}</div><div className="risk-note">最终权限＝所有有效角色权限并集，再受数据范围、有效期和高风险审批限制。支付密钥、正式发布和完整数据导出不会因普通角色叠加自动获得。</div></article>}
function Audit(){const [data,setData]=useState<any[]>([]);useEffect(()=>{operationsFetch<{data:any[]}>("/audit").then(x=>setData(x.data)).catch(()=>setData([]))},[]);return <section className="admin-page"><article className="admin-panel admin-table-panel"><Head en="AUDIT LOG" title={`操作审计 · ${data.length}`}/>{data.length?<table><thead><tr><th>时间</th><th>操作人</th><th>操作</th><th>业务对象</th><th>详情</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString("zh-CN")}</td><td>{String(x.actor_user_id||"系统").slice(0,8)}</td><td>{cn(x.action)}</td><td>{x.resource_type} · {String(x.resource_id||"").slice(0,8)}</td><td><button className="admin-link" title={JSON.stringify(x.metadata)}>查看记录</button></td></tr>)}</tbody></table>:<div className="empty-state"><b>暂无审计记录</b><span>所有高风险操作都必须可追踪。</span></div>}</article></section>}
function Placeholder({title,text}:{title:string;text:string}){return <article className="admin-panel placeholder-panel"><span>建设范围已定义</span><h2>{title}</h2><p>{text}</p><button className="admin-secondary">查看配置字段清单</button></article>}
function Pagination(){return <div className="pagination"><span>共 38 条 · 每页 20 条</span><button disabled>上一页</button><button className="is-active">1</button><button>2</button><button>下一页</button></div>}
function Toolbar({placeholder,button}:{placeholder:string;button:string}){return <div className="admin-toolbar"><label className="admin-search">⌕<input placeholder={placeholder}/></label><button className="admin-primary">{button}</button><span className="admin-hint">默认隐藏敏感信息，完整手机号仅在授权后显示</span></div>}
function Tabs({items}:{items:string[]}){return <div className="admin-tabbar">{items.map((x,i)=><button className={i===0?"is-active":""} key={x}>{x}</button>)}</div>}
function Head({en,title}:{en:string;title:string}){return <div className="admin-panel-head"><div><p className="admin-eyebrow">{en}</p><h2>{title}</h2></div></div>}
function Task({tone,title,note,action,click}:{tone:string;title:string;note:string;action:string;click:()=>void}){return <div className="admin-task"><span className={`admin-dot is-${tone}`}/><div><strong>{title}</strong><p>{note}</p></div><button onClick={click}>{action}</button></div>}
function Stat({a,b,c}:{a:string;b:string;c:string}){return <article className="admin-stat"><p>{a}</p><strong>{b}</strong><small>{c}</small></article>}
function Tag({value}:{value:string}){const cls=/异常/.test(value)?"danger":/待|预占|未发放/.test(value)?"warn":"";return <em className={`tag ${cls}`}>{value}</em>}
function Info({a,b}:{a:string;b:string}){return <div><small>{a}</small><b>{b}</b></div>}
