"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { api,type DailyInsight,type HomeOverview,type WisdomSeedAccount,type WisdomSeedTransaction } from "@/src/api/client";
import { LegacyDomainRoute } from "@/src/features/legacy/LegacyDomainRoute";
import { ComingSoonPage,MyHome,MyReports,MySeeds,MySettings,MySupport,type HomeNavTarget } from "@/src/features/legacy/LegacyProfileFlow";
import { ProtectedRoute } from "@/src/shared/guards";
import { queryOnce,readQueryCache } from "@/src/shared/query";
import { dailyReportPath,ROUTES,withReturnPath } from "@/src/shared/routes";
import { RouteError,RouteFrame,RouteSkeleton } from "@/src/shared/shell";
import { useSession } from "@/src/shared/session";
import { apiMessage } from "@/src/shared/ui";

export function MyHomeScreen(){
  const[home,setHome]=useState<HomeOverview|null>(()=>readQueryCache<HomeOverview>("home:overview")??null);const[state,setState]=useState<"home"|"settings"|"support"|"成长"|"关系">("home");const[error,setError]=useState("");const router=useRouter();const{logout}=useSession();
  useEffect(()=>{let active=true;void queryOnce("home:overview",()=>api.home()).then(v=>active&&setHome(v)).catch(e=>active&&setError(apiMessage(e)));return()=>{active=false;};},[]);
  if(error)return <RouteError message={error}/>;if(!home)return <ProtectedRoute><RouteSkeleton/></ProtectedRoute>;
  const open=(action:string)=>{if(action==="home")router.push(ROUTES.home);else if(action==="daily")router.push(ROUTES.daily);else if(action==="profile")router.push(ROUTES.myProfile);else if(action==="benefits")router.push(withReturnPath(ROUTES.myBenefits,ROUTES.my));else if(action==="membership")router.push(withReturnPath(ROUTES.serviceMembership,ROUTES.my));else if(action==="services")router.push(withReturnPath(ROUTES.services,ROUTES.my));else if(action==="orders")router.push(withReturnPath(ROUTES.myOrders,ROUTES.my));else if(action==="seeds")router.push(ROUTES.mySeeds);else if(action==="settings")setState("settings");else if(action==="support")setState("support");else if(action==="archive")router.push(ROUTES.myArchive);};
  const navigate=(target:HomeNavTarget)=>{if(target==="today")router.push(ROUTES.home);else if(target==="reading")router.push(ROUTES.readings);else if(target==="my")setState("home");else setState(target==="relationship"?"关系":"成长");};const preview=state==="成长"||state==="关系"?state:null;
  return <ProtectedRoute><RouteFrame title={preview??"我的"} label="我的首页">{preview?<ComingSoonPage kind={preview} navigate={navigate}/>:state==="settings"?<MySettings busy={false} onBack={()=>setState("home")} onLogout={()=>void logout()}/>:state==="support"?<MySupport onBack={()=>setState("home")}/>:<MyHome name={home.profile.displayName} balance={home.wisdomSeedAccount.available} open={open} navigate={navigate}/>}</RouteFrame></ProtectedRoute>;
}
export function MyProfileScreen(){return <LegacyDomainRoute title="我的档案" label="本人档案" initialStep={22}/>;}
export function MySeedsScreen(){const[account,setAccount]=useState<WisdomSeedAccount|null>(null);const[transactions,setTransactions]=useState<WisdomSeedTransaction[]>([]);const[error,setError]=useState("");const router=useRouter();useEffect(()=>{let active=true;void Promise.all([queryOnce("my:seeds",()=>api.seedAccount()),queryOnce("my:seed-transactions",()=>api.seedTransactions())]).then(([a,t])=>{if(active){setAccount(a);setTransactions(t);}}).catch(e=>active&&setError(apiMessage(e)));return()=>{active=false;};},[]);if(error)return <RouteError message={error}/>;if(!account)return <ProtectedRoute><RouteSkeleton/></ProtectedRoute>;return <ProtectedRoute><RouteFrame title="AI 体验额度" label="平台赠送额度"><MySeeds account={account} transactions={transactions} onBack={()=>router.push(ROUTES.my)}/></RouteFrame></ProtectedRoute>;}
export function MyReportsScreen(){const[home,setHome]=useState<HomeOverview|null>(null);const[insight,setInsight]=useState<DailyInsight|null>(null);const[error,setError]=useState("");const router=useRouter();useEffect(()=>{let active=true;void queryOnce("my:reports-home",()=>api.home()).then(async overview=>{if(!active)return;setHome(overview);if(overview.dailyInsight.localDate){try{const daily=await queryOnce(`daily:${overview.dailyInsight.localDate}`,()=>api.dailyInsight(overview.dailyInsight.localDate!));if(active)setInsight(daily);}catch{}}}).catch(e=>active&&setError(apiMessage(e)));return()=>{active=false;};},[]);if(error)return <RouteError message={error}/>;if(!home)return <ProtectedRoute><RouteSkeleton/></ProtectedRoute>;return <ProtectedRoute><RouteFrame title="我的报告" label="报告列表"><MyReports home={home} insight={insight} onBack={()=>router.push(ROUTES.my)} onDaily={()=>home.dailyInsight.localDate&&router.push(dailyReportPath(home.dailyInsight.localDate,"my-reports"))}/></RouteFrame></ProtectedRoute>;}
export function GrowthRecordsScreen(){
  const[type,setType]=useState<"全部"|"每日指引"|"抽卡问事">("全部");
  const[state,setRecordState]=useState<"全部状态"|"已完成"|"生成中">("全部状态");
  const router=useRouter();
  const records=[
    {id:"daily-today",kind:"每日指引" as const,state:"已完成" as const,date:"2026.08.25",title:"今天适合把重要的事慢慢理清",summary:"今日能量 · 中｜适合整理、沟通与稳步推进",meta:"今日更新",action:()=>router.push(dailyReportPath("2026-08-25","growth-records"))},
    {id:"reading-work",kind:"抽卡问事" as const,state:"已完成" as const,date:"2026.08.24",title:"现在的工作变化，我应该如何选择？",summary:"3张卡牌 · 完整问事报告",meta:"昨天",action:()=>router.push(withReturnPath("/readings/report?cards=3",ROUTES.myGrowthRecords))},
    {id:"reading-relation",kind:"抽卡问事" as const,state:"生成中" as const,date:"2026.08.25",title:"这段关系中，我真正需要看见什么？",summary:"2张卡牌 · 报告正在生成",meta:"预计还需1分钟",action:()=>router.push(withReturnPath("/readings/generating?cards=2",ROUTES.myGrowthRecords))},
    {id:"daily-previous",kind:"每日指引" as const,state:"已完成" as const,date:"2026.08.23",title:"先照顾好自己的节奏，再回应外界",summary:"今日能量 · 高｜适合表达、决定与主动连接",meta:"2天前",action:()=>router.push(dailyReportPath("2026-08-23","growth-records"))},
  ];
  const shown=records.filter(record=>(type==="全部"||record.kind===type)&&(state==="全部状态"||record.state===state));
  return <ProtectedRoute><RouteFrame title="成长记录" label="R1.1 · MY-19"><section className="growth-records-page"><header className="growth-records-header"><button type="button" onClick={()=>router.push(ROUTES.my)} aria-label="返回">‹</button><strong>成长记录</strong><button type="button" onClick={()=>router.push(ROUTES.readingHistory)}>问事历史</button></header><section className="growth-records-hero"><small>MY GROWTH RECORDS</small><h1>每一次看见<br/>都在这里留下痕迹</h1><p>统一回看每日指引与抽卡问事结果。</p><div><span><strong>4</strong><small>全部记录</small></span><span><strong>2</strong><small>每日指引</small></span><span><strong>2</strong><small>抽卡问事</small></span></div></section><div className="growth-record-tabs">{(["全部","每日指引","抽卡问事"] as const).map(item=><button type="button" className={type===item?"active":""} onClick={()=>setType(item)} key={item}>{item}</button>)}</div><div className="growth-record-toolbar"><strong>{type} · {shown.length}条</strong><select aria-label="筛选记录状态" value={state} onChange={event=>setRecordState(event.target.value as typeof state)}><option>全部状态</option><option>已完成</option><option>生成中</option></select></div><div className="growth-record-list">{shown.map(record=><button type="button" className={record.state==="生成中"?"generating":""} onClick={record.action} key={record.id}><i>{record.kind==="每日指引"?"日":"问"}</i><span><small>{record.kind} · {record.date}</small><strong>{record.title}</strong><p>{record.summary}</p><em>{record.meta}</em></span><b>{record.state==="生成中"?"…":"›"}</b></button>)}</div>{shown.length===0&&<div className="growth-record-empty"><i>芽</i><strong>暂时没有这类记录</strong><p>换一个分类或状态看看。</p></div>}</section></RouteFrame></ProtectedRoute>;
}
export function MyArchiveScreen(){return <LegacyDomainRoute title="人物档案库" label="人物档案库" initialStep={111}/>;}
