server {
  listen 80;
  server_name operations.test.shenxinyou.com;

  location /operations-api/ {
    proxy_pass http://127.0.0.1:3210/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Request-Id $request_id;
    proxy_set_header X-Forwarded-Proto http;
  }

  location / {
    proxy_pass http://127.0.0.1:6900;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto http;
  }
}
