import type { DailyInsight, HomeOverview, LifeProfile, ProfileFirstLook, ProfileRevision, WisdomSeedAccount, WisdomSeedTransaction } from "@/src/api/client";

const now="2026-08-24T10:00:00.000Z";
export const prototypeCards=[
  {dimension:"SPACETIME",title:"时空关系卡牌",order:1,cardId:7,cardCode:"07-gengwu",ganzhi:"庚午",zodiac:"马",season:"夏",talentMark:"行动力",abilityMark:"一",journeyMark:"光与热",deckCode:"SATORI_DEFAULT",deckVersion:"1.0",assetUrl:"/cards/satori-default-v1/07-gengwu.jpg",altText:"庚午生命智慧卡牌",summary:"你愿意走向更大的世界，也需要为热烈找到方向。"},
  {dimension:"CAREER",title:"事业关系卡牌",order:2,cardId:18,cardCode:"18-xinsi",ganzhi:"辛巳",zodiac:"蛇",season:"夏",talentMark:"辨识力",abilityMark:"二",journeyMark:"智与动",deckCode:"SATORI_DEFAULT",deckVersion:"1.0",assetUrl:"/cards/satori-default-v1/18-xinsi.jpg",altText:"辛巳生命智慧卡牌",summary:"你对价值与品质敏锐，越专注越容易被看见。"},
  {dimension:"FAMILY",title:"家庭关系卡牌",order:3,cardId:1,cardCode:"01-jiazi",ganzhi:"甲子",zodiac:"鼠",season:"春",talentMark:"领导力",abilityMark:"一",journeyMark:"生与仁",deckCode:"SATORI_DEFAULT",deckVersion:"1.0",assetUrl:"/cards/satori-default-v1/01-jiazi.jpg",altText:"甲子生命智慧卡牌",summary:"你重视关系里的真诚，也常常是重新开始的人。"},
  {dimension:"SELF",title:"自我关系卡牌",order:4,cardId:5,cardCode:"05-wuchen",ganzhi:"戊辰",zodiac:"龙",season:"春",talentMark:"承载力",abilityMark:"三",journeyMark:"生与仁",deckCode:"SATORI_DEFAULT",deckVersion:"1.0",assetUrl:"/cards/satori-default-v1/05-wuchen.jpg",altText:"戊辰生命智慧卡牌",summary:"你的力量来自稳稳扎根，把复杂的事一步步变简单。"},
] as unknown as NonNullable<ProfileRevision["cards"]>;

export const prototypeRevision={revisionId:"prototype-revision",revisionNumber:1,status:"ACTIVE",inputFingerprint:"prototype-fingerprint",cards:prototypeCards,requiresEnhancedConfirmation:false,warnings:[],confirmedAt:now} as ProfileRevision;
export const prototypeFirstLook={reportId:"prototype-first-look",profileRevisionId:"prototype-revision",status:"READY",content:{schemaVersion:"1.0.0",status:"complete",profileSummary:{title:"在热烈与安定之间，找到自己的节奏",description:"你有向外照亮的热情，也有把想法变成现实的耐力。真正适合你的，不是一味用力，而是在热烈与安定之间找到自己的节奏。",keywords:["明亮","稳定","有方向"],outerTrait:"主动而有感染力",innerTrait:"重视秩序与落地"},cards:[
  {position:"year",dimension:"思想",card:"庚午",title:"让热烈拥有方向",summary:"你愿意走向更大的世界，也需要为热烈找到方向。",innerTrait:"渴望清晰",outerTrait:"主动开拓",status:"complete",evidence:{card:"庚午"},missingFields:[]},
  {position:"month",dimension:"事业",card:"辛巳",title:"用专注建立价值",summary:"你对价值与品质很敏锐，越专注越容易被看见。",innerTrait:"标准清晰",outerTrait:"重视品质",status:"complete",evidence:{card:"辛巳"},missingFields:[]},
  {position:"day",dimension:"行为",card:"甲子",title:"在关系中开启新局",summary:"你重视关系里的真诚，也常常是重新开始的那个人。",innerTrait:"看重真诚",outerTrait:"敢于开始",status:"complete",evidence:{card:"甲子"},missingFields:[]},
  {position:"hour",dimension:"梦想目标",card:"戊辰",title:"把复杂变得简单",summary:"你的力量来自稳稳扎根，把复杂的事一步步变简单。",innerTrait:"需要稳定",outerTrait:"善于承载",status:"complete",evidence:{card:"戊辰"},missingFields:[]},
],knowledgeRelease:"prototype-r1.0",notice:"这是一份基础认识，不是对你人生的定论。"},manifest:{workflowVersion:"prototype",skillVersion:"prototype",model:"prototype",promptVersion:"prototype",outputSchemaVersion:"1.0.0",contentPolicyVersion:"prototype"},failure:null,generatedAt:now,createdAt:now,updatedAt:now} as ProfileFirstLook;
export const prototypeAccount={accountId:"prototype-account",available:18,reserved:0,totalEarned:18,totalSpent:0,updatedAt:now} as WisdomSeedAccount;
export const prototypeTransactions=[{transactionId:"prototype-grant",type:"GRANT",amount:18,balanceAfter:18,businessType:"REGISTRATION_REWARD",resourceId:"prototype-reward",title:"新手启程礼",createdAt:now}] as WisdomSeedTransaction[];
export const prototypeProfiles=[
  {profileId:"prototype-profile",subjectId:"prototype-user",subjectType:"SELF",displayName:"小满",relationshipType:"SELF",currentRevisionId:"prototype-revision",state:"ACTIVE",updatedAt:now},
  {profileId:"prototype-mother",subjectId:"prototype-mother",subjectType:"OTHER",displayName:"妈妈",relationshipType:"FAMILY",currentRevisionId:"prototype-revision-mother",state:"ACTIVE",updatedAt:now},
  {profileId:"prototype-friend",subjectId:"prototype-friend",subjectType:"OTHER",displayName:"周言",relationshipType:"FRIEND",currentRevisionId:"prototype-revision-friend",state:"ACTIVE",updatedAt:now},
] as LifeProfile[];
export const prototypeDailyInsight={dailyInsightId:"prototype-daily",localDate:"2026-08-24",timezone:"Asia/Shanghai",status:"READY",profileRevisionId:"prototype-revision",content:{theme:"稳稳推进",insight:"今天适合把注意力放回真正重要的事情。",action:"选择一件重要的事，完整推进一步。",reflectionQuestion:"今天最值得我认真完成的是什么？",notice:"AI 内容仅供自我觉察参考。"},taskId:null,settlement:{currency:"WISDOM_SEED",amount:1,status:"CONSUMED",transactionId:"prototype-daily-tx"},publishedAt:now,createdAt:now} as DailyInsight;
export const prototypeHome={user:{userId:"prototype-user",timezone:"Asia/Shanghai"},profile:prototypeProfiles[0],cards:prototypeCards,registrationReward:{rewardId:"prototype-reward",rewardType:"NEW_USER_ONBOARDING",status:"CLAIMED",wisdomSeedAmount:18,claimedAt:now},wisdomSeedAccount:prototypeAccount,dailyInsight:{localDate:"2026-08-24",state:"READY",dailyInsightId:"prototype-daily",taskId:null},dailyEnergySummary:{state:"READY",data:{greeting:"小满，你好",guidance:"把注意力放回真正重要的事情，今天适合稳稳推进。",energyLevel:"中",suitableActions:["整理计划","推进一件重要的事"],cautions:["避免同时开始太多任务","给情绪留一点空间"],date:"2026-08-24",dayCard:"甲子",heavenCard:"庚午",score:68,signals:["prototype"],ruleVersion:"prototype",copyVersion:"prototype"}},nextAction:"VIEW_HOME"} as HomeOverview;
