import React, {useState, useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import './reference/h5-globals.css';
import './reference/h5-legacy.css';
import './reference/h5-responsive.css';
import './style.css';

const copy = value => JSON.parse(JSON.stringify(value));
const initialConfig = {labels:false, modes:[1,2,3], menus:[{id:'home',name:'首页',visible:true},{id:'ask',name:'问事',visible:true},{id:'relations',name:'关系',visible:true},{id:'growth',name:'成长',visible:true},{id:'mine',name:'我的',visible:true}]};
const envNames={prototype:'原型环境',test:'测试环境',production:'正式环境'};
const defaultStore=Object.fromEntries(Object.keys(envNames).map(key=>[key,{published:copy(initialConfig),draft:null,previous:null,version:1,logs:[]}]));
function readStore(){try{return JSON.parse(localStorage.getItem('wfh-prototype-config-v2'))||copy(defaultStore);}catch{return copy(defaultStore);}}
const pages={welcome:['AUTH-02','欢迎'],login:['AUTH-03','从认识自己开始'],profile:['PROFILE-01','建立生命智慧档案'],cards:['PROFILE-11','你的生命智慧卡牌'],basic:['REPORT-01','初识你的五福'],seed:['SEED-01','收下这份见面礼'],loading:['DAILY-02','正在整理今日指引'],failure:['DAILY-12','这次指引还没准备好'],insufficient:['SEED-02','体验权益暂未就绪'],daily:['DAILY-03','每日指引'],home:['HOME-01','首页'],ask:['READ-01','抽卡问事'],draw:['READ-10','你的卡牌'],reading:['READ-15','小岁说 · 问事报告'],share:['SHARE-04','分享预览'],mine:['MY-01','我的'],history:['MY-04','我的报告'],relations:['RELATION-01','关系'],growth:['GROWTH-01','成长']};
const assets=['01-jiazi','44-dingwei','07-gengwu','49-renzi'];
const baseProfile={name:'清禾',birth:'1992-06-18',time:'09:30',place:'上海'};
const blankUser={logged:false,profile:false,firstDone:false,daily:false,seed:false,page:'welcome',data:baseProfile,task:null,reading:false};
function readUser(){try{return JSON.parse(sessionStorage.getItem('wfh-prototype-user-v1'))||copy(blankUser);}catch{return copy(blankUser);}}
const issue=(n)=>`https://github.com/jiucongtian/M-satori/issues/${132+n}`;
const storyNames=['产品内品牌统一','分享品牌统一','小岁统一讲述体验','基础报告五福化','每日指引五福化','问事报告五福化','控制页面编号显示','配置开放的抽卡模式','模式调整后继续已有服务','配置底部导航','新用户先体验每日指引','从外发链接获得自己的指引','老用户直接复用已有资料','中断后继续首次体验','明确首次指引的权益消耗','POC 中的小岁与五福结构'];
function Icon({name,size=20}){const paths={home:'M3 10l9-7 9 7v10H3z M9 20v-7h6v7',ask:'M21 11a9 8 0 0 1-9 8H5l-3 3 1-7a8 8 0 1 1 18-4z',relations:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M1 21v-3a7 7 0 0 1 14 0v3 M16 4a4 4 0 0 1 0 8 M18 15a6 6 0 0 1 5 6',growth:'M12 22V10 M12 14C3 14 2 8 3 3c6 0 9 4 9 11 M12 17c9 0 10-7 9-11-6 0-9 4-9 11',mine:'M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M4 22v-4a8 8 0 0 1 16 0v4z',arrow:'M9 5l7 7-7 7',back:'M15 5l-7 7 7 7',check:'M4 12l5 5L20 6',menu:'M4 6h16 M4 12h16 M4 18h16',file:'M5 2h9l5 5v15H5z M14 2v6h5 M8 12h8 M8 16h5',cards:'M3 3h18v18H3z M3 9h18 M7 13v4 M12 13v4 M17 13v4',info:'M12 8v1 M12 12v5 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',close:'M5 5l14 14 M19 5L5 19',up:'M5 15l7-7 7 7',down:'M5 9l7 7 7-7',refresh:'M20 8A9 9 0 1 0 21 15 M20 2v6h-6'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.file}/></svg>;}
function Button({children,onClick,secondary=false,disabled=false,className='',type='button'}){return <button type={type} disabled={disabled} onClick={onClick} className={`${secondary?'secondary':'primary'} ${className}`}>{children}</button>}
function Persona(){return <div className="persona"><div className="avatar-placeholder">小岁画像<br/>待提供</div><p>小岁陪你读懂五福，<br/>照顾当下的自己。</p></div>}
function SampleNote(){return <p className="sample-note">示例内容 · 正式模板待提供</p>}
function BottomNav({config,page,onNavigate}){return <nav className="bottom-nav" aria-label="用户导航">{config.menus.filter(m=>m.visible).map(m=><button key={m.id} className={page===m.id?'selected':''} onClick={()=>onNavigate(m.id)}><Icon name={m.id}/><span>{m.name}</span></button>)}</nav>}
function CardSet({count=4,flipped=true,onClick}){return <div className={`card-set count-${count}`}>{Array.from({length:count},(_,i)=><button className="life-card" key={i} onClick={onClick} aria-label={flipped?`查看第 ${i+1} 张示例卡`:`翻开第 ${i+1} 张卡`} disabled={!onClick}>{flipped?<img src={`/cards/${assets[i%4]}.png`} alt={`第 ${i+1} 张演示卡牌`}/>:<div className="card-back"><span>五福荟</span><small>轻触翻牌</small></div>}</button>)}</div>}
function Brand(){return <span className="brand brand-compact"><span><strong>五福荟</strong><small>生命智慧</small></span></span>}
function Phone({config,page,onNavigate,children,nav=false,title,back,onBack}){return <section className={`phone profile-mode wfh-phone ${page==='home'?'wfh-home':''}`} aria-label="用户端预览"><div className="ambient ambient-one"/><div className="ambient ambient-two"/>{config.labels&&<small className="screen-id">wufuhui R1.1 · {pages[page]?.[0]}</small>}{page!=='welcome'&&<header className="wfh-mobile-header">{back?<button className="icon-button" onClick={onBack||(()=>onNavigate('home'))} aria-label="返回"><Icon name="back"/></button>:null}<Brand/>{page==='home'&&<div className="seed-balance"><span>智慧种子</span><strong>—</strong></div>}</header>}<div className="wfh-content" key={page}>{children}</div>{nav&&<BottomNav config={config} page={page} onNavigate={onNavigate}/>}</section>}
function Welcome({onStart}){return <><header className="brand-row"><Brand/></header><div className="hero-copy"><p className="eyebrow">YOUR INNER SEASONS</p><h1>每一天，<br/><em>更懂自己一点</em></h1><p className="intro">从你的出生时刻出发，读懂当下的节律，找到适合自己的下一步。</p></div><div className="life-orbit" aria-hidden="true"><div className="orbit orbit-outer"><b/><b/><b/></div><div className="orbit orbit-middle"/><div className="sun"><span>此刻</span><strong>遇见自己</strong></div><span className="leaf leaf-a"/><span className="leaf leaf-b"/><span className="leaf leaf-c"/></div><div className="bottom-panel"><div className="trust-note"><span className="lock"/><span>你的出生资料默认仅自己可见，也可以随时管理</span></div><Button onClick={onStart}>开始认识自己 <Icon name="arrow"/></Button></div></>}
function HomeReference({name,user,onNext}){return <section className="today-home"><div className="today-home-scroll"><p className="eyebrow">TODAY · 2026-09-11</p><h1>{name}，你好</h1><article className="daily-guide home-energy-card"><div className="energy-scale"><small>今日能量</small><div>{['高','中','低'].map(v=><span key={v}>{v}</span>)}</div></div><p className="guide-kicker">TODAY'S GUIDANCE</p><h2>把注意力放回真正重要的事情，<br/>今天适合稳稳推进。</h2><div className="home-growth-scene" aria-hidden="true"><div className="life-growth"><i className="living-seed"/><i className="living-stem"/><i className="living-leaf leaf-left"/><i className="living-leaf leaf-right"/><i className="living-leaf leaf-top"/><span className="growth-ring ring-one"/><span className="growth-ring ring-two"/></div></div><div className="guide-tips"><div><small>适合做什么</small><strong>整理计划<br/>推进一件重要的事</strong></div><div><small>注意什么</small><strong>给情绪留一点空间<br/>避免同时开始太多任务</strong></div></div><button className="home-guidance-link" onClick={onNext}>{user.daily?'查看今日能量指引':'继续今日能量指引'}<Icon name="arrow"/></button></article><p className="help">沿用首页能量卡结构 · 当前为示例，无真实评分</p></div></section>}
function Report({kind,name,action}){const daily=kind==='daily',basic=kind==='basic';return <section className="daily-page daily-report"><div className="report-scroll"><p className="eyebrow">{daily?'TODAY · 2026-09-11':'LIFE WISDOM'}</p><h1>{name}的{daily?'今日能量指引':basic?'生命智慧报告':'问事解读'}</h1><Persona/><SampleNote/>{daily&&<div className="energy-header"><div><span>—</span><small>今日能量</small></div><p><small>今日关键词</small><strong>回到自己的节奏</strong></p></div>}<article className="report-opening"><b>小岁说</b><h2>{basic?'从四张牌，慢慢认识自己':'把重要的事，放在心静之后'}</h2><p>小岁想邀请你，先把目光放回自己。</p></article><section className="wfh-template"><h2>从五福，看见与你的关系</h2><p>这一区域将按确认后的{basic?'基础报告':daily?'每日指引':'问事报告'}模板展开。当前展示阅读结构，不编造五福映射或命理解读。</p><div className="five-fortunes">{['福','禄','寿','喜','财'].map(v=><span key={v}>{v}</span>)}</div></section><div className="report-columns"><article><small>今日行动</small><h3>从一件小事开始</h3><p>选一件最重要的事，慢慢完成。</p></article><article><small>今日反思</small><h3>问问自己</h3><p>此刻对我真正重要的是什么？</p></article></div><blockquote>小岁想对你说：给自己留一点时间，你的感受值得被认真听见。</blockquote>{action}</div></section>}
function Login({onLogin}){const [phone,setPhone]=useState('13800000000'),[code,setCode]=useState(''),[agreed,setAgreed]=useState(false),[sent,setSent]=useState(false),[message,setMessage]=useState(''),[policy,setPolicy]=useState(false);return <><div className="login-intro"><h1>从认识自己开始</h1><p>建立你的生命智慧档案</p></div><form onSubmit={e=>{e.preventDefault();if(!/^1\d{10}$/.test(phone)){setMessage('请输入 11 位演示手机号');return;}if(code!=='123456'){setMessage('请使用演示验证码 123456');return;}onLogin();}}><label className="field"><span>手机号</span><input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} aria-label="手机号"/></label><label className="field"><span>验证码</span><div className="input-action"><input value={code} inputMode="numeric" onChange={e=>setCode(e.target.value)} placeholder="6 位验证码" aria-label="验证码"/><button type="button" onClick={()=>{setSent(true);setCode('123456');}}>获取验证码</button></div></label>{sent&&<p className="help">演示验证码已填入，不发送真实短信。</p>}<label className="agreement"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>我已阅读并同意 <button type="button" className="text-button" onClick={()=>setPolicy(!policy)}>用户协议和隐私政策</button></span></label>{policy&&<div className="notice">这是交互原型，不提交手机号或出生资料。正式协议沿用产品已确认内容，当前展示协议入口与勾选交互。</div>}{message&&<p role="alert" className="error">{message}</p>}<Button type="submit" disabled={!agreed}>登录并继续</Button></form><p className="quiet-footer">只使用演示资料，不连接真实账户</p></>}
function ProfileForm({data,onSubmit}){const [draft,setDraft]=useState(data);return <><h1>先认识此刻的你</h1><p className="muted">填写演示资料，看看建档后的体验。</p><form onSubmit={e=>{e.preventDefault();onSubmit(draft);}}>{[['name','你的称呼','text'],['birth','出生日期','date'],['time','出生时间','time'],['place','出生地点','text']].map(([key,label,type])=><label className="field" key={key}><span>{label}</span><input required maxLength={key==='name'?12:80} type={type} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<p className="help">卡牌为固定示例，不根据输入进行真实排盘。</p><Button type="submit">确认资料，查看卡牌</Button></form></>}
function AskForm({config,onStart,initialQuestion='',preview=false}){const [question,setQuestion]=useState(initialQuestion),[mode,setMode]=useState(config.modes[0]),[error,setError]=useState('');useEffect(()=>{if(!config.modes.includes(mode))setMode(config.modes[0]);},[config.modes.join(',')]);return <><h1 className="ask-title">今天，你想问什么？</h1><label className="field"><textarea maxLength={200} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="在这里输入你想问的问题……" aria-label="想问的问题"/><span className="counter">{question.length}/200</span></label><h3>选择抽卡模式</h3><div className="mode-options">{config.modes.map(n=><label key={n}><input type="radio" name={preview?'preview-mode':'mode'} checked={mode===n} onChange={()=>setMode(n)}/><span>{n===1?'单卡':n===2?'双卡':'多卡'} <small>（抽取 {n===3?'3':n} 张卡牌）</small></span></label>)}</div>{preview&&<p className="help">预览当前草稿</p>}{error&&<p className="error" role="alert">{error}</p>}<Button onClick={()=>{if(!question.trim()){setError('先写下你想问的事');return;}onStart(question,mode);}}>开始抽卡</Button></>}
function UserExperience({config,user,setUser,scenario,setScenario,notify,external=false}){
 const [flipped,setFlipped]=useState(false),[sharedKind,setSharedKind]=useState('daily');
 const go=page=>setUser(u=>({...u,page}));
 const startDaily=()=>setUser(u=>({...u,page:u.daily?'daily':scenario==='insufficient'?'insufficient':'loading',task:u.daily?u.task:'daily-demo-task'}));
 useEffect(()=>{if(user.page!=='loading')return;const timer=setTimeout(()=>{if(scenario==='failure')go('failure');else setUser(u=>({...u,page:'daily',daily:true}));},1500);return ()=>clearTimeout(timer);},[user.page,scenario]);
 function navigate(page){if(!config.menus.find(m=>m.id===page)?.visible&&['home','ask','relations','growth','mine'].includes(page)){notify('该入口已在当前配置中隐藏');return;}go(page);}
 function share(kind){setSharedKind(kind);go('share');}
 let body;
 switch(user.page){
 case 'welcome':body=<Welcome onStart={()=>go('login')}/>;break;
 case 'login':body=<Login onLogin={()=>setUser(u=>({...u,logged:true,page:u.profile?(external?(u.daily?'daily':'loading'):'home'):'profile'}))}/>;break;
 case 'profile':body=<ProfileForm data={user.data} onSubmit={data=>setUser(u=>({...u,data,profile:true,page:'cards'}))}/>;break;
 case 'cards':body=<><h1>{user.data.name}，<br/>这是你的四张卡</h1><p className="muted">从不同角度，认识自己的生命底色。</p><CardSet/><SampleNote/><div className="flow-footer"><Button onClick={()=>go('basic')}>阅读基础报告</Button></div></>;break;
 case 'basic':body=<Report kind="basic" name={user.data.name} action={<><Button onClick={()=>go(user.seed?'home':'seed')}>{user.seed?'回到首页':'继续，领取见面礼'}</Button><button className="text-button wide" onClick={()=>share('basic')}>分享这份初识</button></>}/>;break;
 case 'seed':body=<><div className="seed-visual" aria-hidden="true"><div className="soil"/><div className="sprout"><i/><i/></div><span>—</span><small>智慧种子</small></div><h1>收下这份见面礼</h1><p>愿每一次探索，都让你更靠近自己。</p><div className="notice">智慧种子与首次体验权益<br/><small>具体额度和消耗方案待确认，原型仅演示领取与继续流程。</small></div><Button onClick={()=>{setUser(u=>({...u,seed:true}));startDaily();}}>领取并查看每日指引</Button></>;break;
 case 'loading':body=<div className="center-state"><div className="spinner"/><h1>小岁正在整理<br/>你的今日指引</h1><p>你可以暂时离开，回来后继续。</p><p className="help">演示任务 · 不调用真实生成服务</p></div>;break;
 case 'failure':body=<div className="center-state"><Icon name="info" size={40}/><h1>再给小岁一点时间</h1><p>这次指引暂时没有生成成功，<br/>你的资料已经保留。</p><Button onClick={()=>{setScenario('success');go('loading');}}>重新尝试</Button><Button secondary onClick={()=>go('home')}>稍后再看，先进入首页</Button><p className="help">“先进入首页”为待确认的异常方案。</p></div>;break;
 case 'insufficient':body=<div className="center-state"><Icon name="info" size={40}/><h1>体验权益暂未就绪</h1><p>首次指引的权益方案尚待确认。<br/>原型在此展示不足时的恢复入口。</p><Button onClick={()=>{setScenario('success');go('loading');}}>模拟权益就绪，继续体验</Button><Button secondary onClick={()=>go('home')}>返回首页</Button></div>;break;
 case 'daily':body=<Report kind="daily" name={user.data.name} action={<><Button onClick={()=>setUser(u=>({...u,firstDone:true,page:'home'}))}>进入首页</Button><button className="text-button wide" onClick={()=>share('daily')}>分享今日指引</button></>}/>;break;
 case 'home':body=<HomeReference name={user.data.name} user={user} onNext={startDaily}/>;break;
 case 'ask':body=<AskForm config={config} initialQuestion={user.question} onStart={(question,mode)=>{setFlipped(false);setUser(u=>({...u,question,mode,task:`reading-${mode}-demo`,page:'draw'}));}}/>;break;
 case 'draw':body=<><h1>让问题，慢慢展开</h1><p>{user.question}</p><CardSet count={user.mode||1} flipped={flipped} onClick={()=>setFlipped(true)}/><p className="help">固定演示卡牌 · 不进行真实随机抽取</p><Button disabled={!flipped} onClick={()=>setUser(u=>({...u,reading:true,page:'reading'}))}>{flipped?'阅读小岁的解读':'轻触卡牌，翻开看看'}</Button></>;break;
 case 'reading':body=<><div className="question-quote">{user.question||'怎样更从容地面对最近的变化？'}</div><Report kind="reading" name={user.data.name} action={<><Button onClick={()=>share('reading')}>分享这份启发</Button><button className="text-button wide" onClick={()=>go('history')}>回到我的报告</button></>}/></>;break;
 case 'share':body=<><h1>把这一刻，分享出去</h1><div className="share-poster"><div className="brand">五福荟</div><span className="gold-rule"/><h2>给自己<br/>一点从容</h2><p>留一点时间，<br/>听听自己的感受。</p><div className="share-bottom">小岁说 · {sharedKind==='daily'?'每日指引':sharedKind==='basic'?'四卡初识':'抽卡问事'}<br/><small>示例内容 · 正式模板待提供</small></div></div><p className="help">预览默认不显示手机号、出生资料和完整问题。</p><Button onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+location.pathname+'?entry=daily');notify('已复制原型每日指引入口');}catch{notify('请复制浏览器地址，在末尾添加 ?entry=daily');}}}>复制每日指引体验链接</Button><button className="text-button wide" onClick={()=>go(sharedKind==='basic'?'basic':sharedKind==='reading'?'reading':'daily')}>返回报告</button></>;break;
 case 'history':body=<><h1>每一次认识自己</h1>{[['基础报告','basic',true],['9月11日 · 每日指引','daily',user.daily],['抽卡问事报告','reading',user.reading]].map(([label,page,enabled])=><button className="report-list-row" key={page} disabled={!enabled} onClick={()=>go(page)}><span>{label}<small>{enabled?'查看报告':'尚未生成'}</small></span><Icon name="arrow"/></button>)}<p className="help">模式关闭后，已经生成的报告仍可查看。</p></>;break;
 case 'mine':body=<><h1>{user.data.name}</h1><p>每一次看见，都是成长的开始。</p><button className="report-list-row" onClick={()=>go('cards')}>生命智慧档案<Icon name="arrow"/></button><button className="report-list-row" onClick={()=>go('history')}>我的报告<Icon name="arrow"/></button><p className="help">当前为演示账户，仅用于原型评审。</p></>;break;
 default:body=<><h1>{pages[user.page]?.[1]}</h1><p className="muted">这里保留现有模块的导航位置。</p><div className="notice">本轮仅评审导航配置，不重构此模块。R1.2 关系匹配不包含在本次原型中。</div><Button onClick={()=>go('home')}>回到首页</Button></>;
 }
 return <Phone config={config} page={user.page} onNavigate={navigate} nav={['home','ask','mine','history','relations','growth'].includes(user.page)} back={['profile','cards','reading','share','history','draw'].includes(user.page)} onBack={()=>go(user.page==='profile'?'login':user.page==='share'?sharedKind==='basic'?'basic':sharedKind==='reading'?'reading':'daily':'home')}>{body}</Phone>;
}
function ConfigPanel({tab,draft,setDraft,save,rollback,version,logs,readOnly,notify}){
 function mode(n){setDraft({...draft,modes:draft.modes.includes(n)?draft.modes.filter(x=>x!==n):[...draft.modes,n].sort()});}
 function menu(i,key,value){setDraft({...draft,menus:draft.menus.map((m,j)=>i===j?{...m,[key]:value}:m)});}
 function move(i,d){let a=copy(draft.menus);[a[i],a[i+d]]=[a[i+d],a[i]];setDraft({...draft,menus:a});}
 return <><div className="admin-panel"><div className="panel-title"><h2>{tab==='labels'?'页面编号显示':tab==='modes'?'抽卡模式开放':tab==='menus'?'用户端导航菜单':'发布记录'}</h2><span>已发布 v{version}</span></div>{readOnly&&<div className="notice">当前为只读角色，可以查看配置，不能编辑或发布。</div>}
 <fieldset disabled={readOnly} className="config-fields">
 {tab==='labels'&&<><div className="setting-row"><div><strong>显示页面编号</strong><p>用于原型评审与测试定位，关闭后不占用页面空间。</p></div><button role="switch" aria-label="显示页面编号" aria-checked={draft.labels} className={`toggle ${draft.labels?'on':''}`} onClick={()=>setDraft({...draft,labels:!draft.labels})}><i/></button></div><div className="notice">编号沿用 H5 页面标识；新增配置页使用 WFH-CFG 前缀临时编号。分享海报不携带页面编号。</div></>}
 {tab==='modes'&&<><table className="config-table"><thead><tr><th>抽卡模式</th><th>卡牌数量</th><th>开放状态</th></tr></thead><tbody>{[1,2,3].map(n=><tr key={n}><td><strong>{n===1?'单卡':n===2?'双卡':'多卡'}</strong></td><td>{n===3?'3—5 张（本演示按 3 张）':`${n} 张`}</td><td><label className="inline-check"><input type="checkbox" checked={draft.modes.includes(n)} disabled={n===1} onChange={()=>mode(n)}/>{n===1?'始终开放':draft.modes.includes(n)?'已开放':'未开放'}</label></td></tr>)}</tbody></table><div className="notice">已开始的问事和历史报告不受影响。单卡必须开放；默认单卡、双卡、多卡全部开放。</div></>}
 {tab==='menus'&&<><table className="config-table"><thead><tr><th>菜单名称</th><th>显示</th><th>顺序</th></tr></thead><tbody>{draft.menus.map((m,i)=><tr key={m.id}><td><input aria-label={`${m.id}菜单名称`} value={m.name} maxLength={6} onChange={e=>menu(i,'name',e.target.value)}/><small>{m.id}</small></td><td><input aria-label={`${m.name}显示`} type="checkbox" disabled={m.id==='home'||m.id==='mine'} checked={m.visible} onChange={e=>menu(i,'visible',e.target.checked)}/></td><td><button className="icon-button" disabled={i===0} onClick={()=>move(i,-1)} aria-label={`${m.name}上移`}><Icon name="up"/></button><button className="icon-button" disabled={i===draft.menus.length-1} onClick={()=>move(i,1)} aria-label={`${m.name}下移`}><Icon name="down"/></button></td></tr>)}</tbody></table><div className="notice">草案保留首页和“我的”为必显项。改名和排序不改变路由与业务权限；字段长度和必显规则待确认。</div></>}
 </fieldset>
 {tab==='history'?<div className="log-list">{logs.length?logs.map((l,i)=><article key={i}><strong>{l.action} · v{l.version}</strong><span>{l.time} · 演示运营</span><p>{l.reason}</p></article>):<p>本环境尚无配置变更记录。</p>}</div>:<div className="config-actions"><Button disabled={readOnly} onClick={save}>保存并立即生效</Button></div>}
 </div><button className="text-button rollback" disabled={readOnly} onClick={rollback}>恢复上一有效版本</button></>;
}
function App(){
 const [settingsOpen,setSettingsOpen]=useState(false);
 const [surface,setSurface]=useState(new URLSearchParams(location.search).get('entry')==='daily'?'h5':'operations');
 const [tab,setTab]=useState('labels'),[env,setEnv]=useState('test'),[store,setStore]=useState(readStore),[draft,setDraft]=useState(()=>copy(readStore().test.draft||readStore().test.published));
 const [user,setUser]=useState(readUser),[scenario,setScenario]=useState('success'),[entry,setEntry]=useState(new URLSearchParams(location.search).get('entry')==='daily'?'external':'main'),[toast,setToast]=useState(''),[modal,setModal]=useState(false),[reason,setReason]=useState(''),[readOnly,setReadOnly]=useState(false),[width,setWidth]=useState('390');
 const current=store[env];
 useEffect(()=>{localStorage.setItem('wfh-prototype-config-v2',JSON.stringify(store));},[store]);
 useEffect(()=>{sessionStorage.setItem('wfh-prototype-user-v1',JSON.stringify(user));},[user]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4200);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{if(['home','ask','mine','relations','growth'].includes(user.page)&&!current.published.menus.find(m=>m.id===user.page)?.visible)setUser(u=>({...u,page:'home'}));},[current.published]);
 const notify=t=>setToast(t);
 function changeEnv(e){setEnv(e);setDraft(copy(store[e].draft||store[e].published));}
 function validate(){if(!draft.modes.includes(1))return '单卡必须保持开放，不能关闭';if(draft.menus.some(m=>!m.name.trim()))return '菜单名称不能为空';if(new Set(draft.menus.filter(m=>m.visible).map(m=>m.name.trim())).size!==draft.menus.filter(m=>m.visible).length)return '可见菜单名称不能重复';return '';}
 function save(){const error=validate();if(error){notify(error);return;}setStore({...store,[env]:{...current,previous:copy(current.published),published:copy(draft),draft:null,version:current.version+1,logs:[{action:'保存并立即生效',version:current.version+1,time:new Date().toLocaleString('zh-CN'),reason:'运营配置即时生效'},...current.logs]}});notify(`${envNames[env]}配置已保存并立即生效`);}
 function rollback(){if(!current.previous){notify('没有可恢复的上一版本');return;}let c=copy(current.previous);setDraft(c);setStore({...store,[env]:{...current,published:c,previous:copy(current.published),version:current.version+1,logs:[{action:'恢复配置',version:current.version+1,time:new Date().toLocaleString('zh-CN'),reason:'恢复上一有效配置'},...current.logs]}});notify('已恢复上一有效配置');}
 const goto=p=>{setSurface('h5');setUser(u=>({...u,page:p}));};
 function reset(kind){const u=copy(blankUser);if(kind!=='new')Object.assign(u,{logged:true,profile:true,seed:true,firstDone:true,daily:kind==='existing',page:kind==='existing'?'daily':'home'});setUser(u);setScenario('success');notify(kind==='new'?'已切换为新用户演示':'已恢复老用户演示资料');}
 const storyIds=surface==='operations'?(tab==='labels'?[7]:tab==='modes'?[8,9]:tab==='menus'?[10]:[7,8,10]):user.page==='daily'?[3,5,11]:user.page==='basic'?[3,4]:user.page==='share'?[2]:user.page==='reading'?[3,6]:[1,11,12,13,14,15];
 return <div className="review-app"><div className="review-toolbar"><strong>五福荟 R1.1</strong><div className="review-switch">{[['operations','运营管理平台'],['h5','H5 用户原型'],['notes','设计对照与故事']].map(([id,label])=><button key={id} className={surface===id?'active':''} onClick={()=>setSurface(id)}>{label}</button>)}</div><span>增量设计评审 · 本地模拟</span></div>
 {surface==='operations'?<div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand">五福荟<small>运营平台</small></div>{[['数据分析','file'],['研发数据中心','growth'],['商品中心','cards'],['系统配置','menu']].map(([t,i])=><button key={t} className={t==='系统配置'?'active':''} onClick={()=>t!=='系统配置'&&notify('此模块沿用现有原型，本轮仅设计系统配置增量')}><Icon name={i}/>{t}</button>)}<div className="admin-account"><span className="account-avatar">A</span><span>admin<small>平台管理员 · 演示</small></span></div></aside><main className="admin-main"><p className="admin-page-id">WFH-CFG-0{tab==='labels'?1:tab==='modes'?2:tab==='menus'?3:4} · 临时编号</p><h1>系统配置</h1><div className="admin-filter"><label>版本 <strong>五福荟 R1.1</strong></label><label>环境 <select value={env} onChange={e=>changeEnv(e.target.value)}>{Object.entries(envNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>角色 <select value={readOnly?'read':'edit'} onChange={e=>setReadOnly(e.target.value==='read')}><option value="edit">配置运营</option><option value="read">只读查看</option></select></label><span className="published">当前 v{current.version}</span></div><div className="admin-info"><Icon name="info"/><span>配置仅影响当前演示环境。保存后立即对当前环境生效，用户端重新读取即可查看效果。</span><button onClick={()=>setSurface('h5')}>查看用户端 <Icon name="arrow" size={14}/></button></div><nav className="admin-tabs">{[['labels','页面编号'],['modes','抽卡模式'],['menus','导航菜单'],['history','变更记录']].map(([id,t])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{t}</button>)}</nav><ConfigPanel tab={tab} draft={draft} setDraft={setDraft} version={current.version} logs={current.logs} readOnly={readOnly} notify={notify} rollback={rollback} save={save}/><div className="issue-strip">关联故事 {storyIds.map(n=><a key={n} href={issue(n)} target="_blank" rel="noreferrer">US-{String(n).padStart(2,'0')} ↗</a>)}</div></main></div>:
 surface==='h5'?<div className="h5-review"><button className="mobile-settings" onClick={()=>setSettingsOpen(!settingsOpen)}>{settingsOpen?'收起演示设置':'演示设置 / 页面导航'}<Icon name={settingsOpen?'up':'down'}/></button><aside className={`scenario-panel ${settingsOpen?'expanded':''}`}><h2>用户端流程</h2><p>延续 H5 原有页面与组件，<br/>查看 R1.1 的变更。</p><label>入口来源<select value={entry} onChange={e=>{setEntry(e.target.value);if(e.target.value==='external')setUser(u=>({...u,page:u.logged&&u.profile?(u.daily?'daily':'loading'):'welcome'}));}}><option value="main">主系统入口</option><option value="external">每日指引外发链接</option></select></label><div className="scenario-buttons"><button onClick={()=>reset('new')}>新用户开始</button><button onClick={()=>reset('existing')}>老用户 · 已有报告</button><button onClick={()=>reset('returning')}>老用户 · 尚无报告</button></div><label>生成场景<select value={scenario} onChange={e=>setScenario(e.target.value)}><option value="success">正常生成</option><option value="failure">生成失败</option><option value="insufficient">体验权益不足</option></select></label><label>预览宽度<select value={width} onChange={e=>setWidth(e.target.value)}>{['320','390','520'].map(w=><option key={w} value={w}>{w} px</option>)}</select></label><label>配置环境<select value={env} onChange={e=>changeEnv(e.target.value)}>{Object.entries(envNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><details open><summary>页面快速查看</summary><div className="page-jumps">{['welcome','login','profile','cards','basic','seed','daily','home','ask','reading','share','history'].map(p=><button key={p} onClick={()=>goto(p)} className={user.page===p?'active':''}>{pages[p][1]}</button>)}</div></details><p className="help">Logo 使用文字占位；小岁和报告模板待提供。资料与状态仅保存在当前浏览器。首次权益、失败跳过等为待确认方案。</p><div className="issue-strip">{storyIds.map(n=><a key={n} href={issue(n)} target="_blank" rel="noreferrer">US-{String(n).padStart(2,'0')}</a>)}</div></aside><main className="mobile-stage" style={{'--preview-width':`${width}px`}}><UserExperience config={current.published} user={user} setUser={setUser} scenario={scenario} setScenario={setScenario} notify={notify} external={entry==='external'}/><p className="preview-caption">原有 H5 视觉基线 · {envNames[env]} v{current.version}</p></main></div>:
 <main className="design-notes"><h1>在原有基础上，更新五福荟 R1.1</h1><p>H5 保留欢迎页生命轨道、首页深绿能量卡、原有报告层级和底部导航。运营端保留深绿侧栏、顶部筛选带、信息带及横向页签，新增能力归入系统配置。</p><div className="reference-links"><a href="https://github.com/jiucongtian/M-satoriSrs/tree/main/h5%E5%8E%9F%E5%9E%8B" target="_blank" rel="noreferrer">H5 原型参考 ↗</a><a href="https://github.com/jiucongtian/M-satoriSrs/tree/main/operations%20portotyp" target="_blank" rel="noreferrer">运营平台原型参考 ↗</a></div><table className="config-table"><thead><tr><th>用户故事</th><th>本轮设计落点</th><th>评审边界</th></tr></thead><tbody>{storyNames.map((name,i)=><tr key={name}><td><a href={issue(i+1)} target="_blank" rel="noreferrer">US-{String(i+1).padStart(2,'0')} · {name}</a></td><td>{i===6?'系统配置 / 页面编号':i===7||i===8?'系统配置 / 抽卡模式':i===9?'系统配置 / 导航菜单':i===15?'报告模板样稿共用':'H5 对应流程与报告'}</td><td>{i===15?'POC 具体入口待提供':i<6?'正式素材 / 模板待提供':i>9?'权益和异常策略待确认':'配置边界为 PRD 草案'}</td></tr>)}</tbody></table><h2>本轮不改动的范围</h2><p>不改正式前后台，不连接真实短信、排盘、生成、支付或权益服务。R1.2 的关系匹配、皮肤和真太阳时不纳入。现有其他模块保持原有定位，本原型不重建其完整业务。</p></main>}
 {toast&&<div className="toast" role="status">{toast}</div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
