"use client";
import { useEffect,useReducer,useRef,useState } from "react"; import { useRouter } from "next/navigation"; import { api,ApiError,type HomeOverview,type ProfileFirstLook,type ProfileRevision } from "@/src/api/client"; import { Calculating,hasCompleteFirstLookCards,ProfileIntro,RelationshipFirstLook,SeedGift,UnifiedProfileForm,birthTimeFromProfileData,type ProfileData } from "@/src/features/legacy/LegacyProfileFlow"; import { ProtectedRoute } from "@/src/shared/guards"; import { RouteFrame } from "@/src/shared/shell"; import { ROUTES } from "@/src/shared/routes"; import { clearFlowDraft,readFlowDraft,writeFlowDraft } from "@/src/shared/storage"; import { useSession } from "@/src/shared/session"; import { apiMessage } from "@/src/shared/ui"; import { initialProfileMachine,profileReducer } from "./profileMachine";
const DEFAULT:ProfileData={name:"",date:"1990-05-18",calendarType:"SOLAR",lunarYear:1990,lunarMonth:4,lunarDay:24,isLeapMonth:false,time:"08:30",accuracy:"准确到分钟",place:"当前版本暂不启用地区校正",locationId:"loc_cn_330100",gender:"FEMALE",relationshipType:"OTHER"};const DRAFT_VERSION=1;
function validDraft(value:unknown):value is ProfileData{return Boolean(value&&typeof value==="object"&&typeof(value as ProfileData).name==="string"&&/^\d{4}-\d{2}-\d{2}$/.test((value as ProfileData).date));}
export default function ProfileCreateScreen(){const[machine,dispatch]=useReducer(profileReducer,initialProfileMachine);const[data,setData]=useState(DEFAULT);const[revision,setRevision]=useState<ProfileRevision|null>(null);const[firstLook,setFirstLook]=useState<ProfileFirstLook|null>(null);const[home,setHome]=useState<HomeOverview|null>(null);const[stage,setStage]=useState(0);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const confirmLock=useRef<string|null>(null);const rewardLock=useRef(false);const{me}=useSession();const router=useRouter();const owner=me?.userId??"unknown";
useEffect(()=>{if(owner==="unknown")return;const timer=window.setTimeout(()=>{const draft=readFlowDraft<unknown>("profile",owner,DRAFT_VERSION);if(validDraft(draft))setData(draft);void api.home().then(value=>{setHome(value);setData(current=>({...current,name:current.name||value.profile.displayName}));}).catch(()=>undefined);},0);return()=>window.clearTimeout(timer);},[owner]);
useEffect(()=>{if(owner==="unknown"||machine.state!=="editing")return;const timer=window.setTimeout(()=>writeFlowDraft("profile",owner,DRAFT_VERSION,data),200);return()=>window.clearTimeout(timer);},[data,machine.state,owner]);
async function preview(){dispatch({type:"PREVIEW"});setBusy(true);setError("");setStage(0);const timers=[500,1100,1700].map((ms,index)=>window.setTimeout(()=>setStage(index+1),ms));try{const[sy,sm,sd]=data.date.split("-").map(Number);const time=birthTimeFromProfileData(data.accuracy,data.time);const value=await api.previewProfile({calendarType:data.calendarType,date:{year:data.calendarType==="LUNAR"?data.lunarYear:sy,month:data.calendarType==="LUNAR"?data.lunarMonth:sm,day:data.calendarType==="LUNAR"?data.lunarDay:sd,isLeapMonth:data.calendarType==="LUNAR"&&data.isLeapMonth},...time,locationId:data.locationId,calculationGender:data.gender});setRevision(value);setStage(4);dispatch({type:"PREVIEW_READY"});}catch(reason){setError(apiMessage(reason));dispatch({type:"FAIL",recoverTo:"calculating"});}finally{timers.forEach(clearTimeout);setBusy(false);}}
async function generateFirstLook(id:string){try{setFirstLook(await api.generateProfileFirstLook(id));}catch{try{setFirstLook(await api.profileFirstLook(id));}catch{setFirstLook(null);}}}
async function confirm(){if(!revision?.inputFingerprint||confirmLock.current===revision.revisionId)return;confirmLock.current=revision.revisionId;setBusy(true);setError("");try{await api.updateSelfProfile(data.name.trim());try{await api.confirmProfile(revision.revisionId,revision.inputFingerprint,Boolean(revision.requiresEnhancedConfirmation));}catch(reason){if(!(reason instanceof ApiError)||reason.code!=="PROFILE_REVISION_ALREADY_CONFIRMED")throw reason;const persisted=await api.profileRevision(revision.revisionId);if(persisted.status!=="ACTIVE")throw reason;setRevision(persisted);}clearFlowDraft("profile");dispatch({type:"CONFIRMED"});if(hasCompleteFirstLookCards(revision))await generateFirstLook(revision.revisionId);}catch(reason){setError(apiMessage(reason));dispatch({type:"FAIL",recoverTo:"confirming"});}finally{confirmLock.current=null;setBusy(false);}}
async function claim(){if(rewardLock.current)return;rewardLock.current=true;setBusy(true);try{if(home?.registrationReward.status!=="CLAIMED")await api.claimRegistrationReward();dispatch({type:"COMPLETE"});router.replace(ROUTES.home);}catch(reason){setError(apiMessage(reason));}finally{rewardLock.current=false;setBusy(false);}}
const body=machine.state==="intro"?<ProfileIntro onNext={()=>dispatch({type:"START"})}/>:machine.state==="editing"?<UnifiedProfileForm data={data} onChange={setData} onNext={preview}/>:machine.state==="calculating"||machine.state==="confirming"||machine.state==="failed"?<><Calculating name={data.name} stage={stage} state={machine.state==="failed"?"failed":machine.state==="confirming"?"complete":"running"} busy={busy} onRetry={()=>{dispatch({type:"RETRY"});void preview();}} onDone={()=>void confirm()}/>{error&&<p className="api-error" role="alert">{error}</p>}</>:machine.state==="first-look"?<RelationshipFirstLook name={data.name} revision={revision} report={firstLook} loading={busy||firstLook?.status==="GENERATING"} onRetry={()=>revision&&void generateFirstLook(revision.revisionId)} onEdit={()=>dispatch({type:"EDIT"})} onSkip={()=>dispatch({type:"FIRST_LOOK_DONE"})} onNext={()=>dispatch({type:"FIRST_LOOK_DONE"})}/>:<SeedGift name={data.name} amount={home?.registrationReward.wisdomSeedAmount??18} claimed={home?.registrationReward.status==="CLAIMED"} busy={busy} onClaim={claim} onNext={()=>router.replace(ROUTES.home)}/>;return <ProtectedRoute><RouteFrame title="建立生命智慧档案" label="建立生命智慧档案"><div className="profile-flow">{body}</div></RouteFrame></ProtectedRoute>;}
