import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import test from 'node:test';
test('用户界面不得直接暴露内部状态枚举',()=>{const forbidden=['TERMINATED_BY_UPGRADE','PROPERTY_LIMIT','ACTIVE'];assert.equal(forbidden.some(x=>/^[\u4e00-\u9fa5]+$/.test(x)),false)});
test('运营账号使用手机号唯一约束、强密码摘要和超级管理员授权',async()=>{const source=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(source,/phone varchar\(20\) not null unique/);assert.match(source,/scryptSync/);assert.match(source,/SUPER_ADMIN_REQUIRED/);assert.match(source,/该手机号已创建运营账号/)});
test('引导超级管理员首次重新登录后转为可维护账号',async()=>{const source=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(source,/authenticateOperationsAccount/);assert.match(source,/insert into operations_accounts/);assert.match(source,/insert into operations_account_roles/);assert.match(source,/accountId:account.id/)});
test('工作台同时提供用户总数和有效订单营收',async()=>{const source=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(source,/total_users/);assert.match(source,/revenue_minor/);assert.match(source,/status in\('PAID','FULFILLING','FULFILLED'\)/)});
test('完整手机号通过安全哈希检索且所有业务记录返回统一用户身份',async()=>{const source=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(source,/createHmac\('sha256',env.AUTH_HMAC_SECRET\)/);assert.match(source,/provider_subject_hash=\$2/);assert.match(source,/withUserIdentity/);assert.match(source,/actor:x.actor_user_id\?userIdentity/)});
test('超级管理员可安全重置或删除普通运营账号',async()=>{const source=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(source,/\/api\/accounts\/:id\/reset-password/);assert.match(source,/app.delete\('\/api\/accounts\/:id'/);assert.match(source,/CANNOT_DELETE_SELF/);assert.match(source,/CONFIGURED_ACCOUNT_PROTECTED/);assert.match(source,/LAST_SUPER_ADMIN/)});
test('订单接口使用真实分页、查询和状态筛选',async()=>{const source=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(source,/pageSize/);assert.match(source,/totalPages/);assert.match(source,/limit \$3 offset \$4/);assert.match(source,/o\.order_number ilike/)});
test('商品草稿、审核和版本发布形成闭环',async()=>{const source=await readFile(new URL('../src/server.ts',import.meta.url),'utf8');assert.match(source,/operations_product_drafts/);assert.match(source,/\/api\/products\/:id\/draft/);assert.match(source,/\/api\/products\/:id\/submit/);assert.match(source,/action\.action_type==='PRODUCT_CHANGE'/);assert.match(source,/insert into offering_versions/);assert.doesNotMatch(source,/商品配置需经版本发布流程执行/)});
