import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';

type Position = 'hour' | 'day' | 'month' | 'year';
interface PositionCopyRow extends Record<Position, string> {
  sequence: number;
  card: string;
}

const [, , sourceArgument, outputArgument] = process.argv;
if (!sourceArgument || !outputArgument) {
  throw new Error('Usage: npx tsx build-position-copy.ts <六十甲子表.md> <output.ts>');
}

const sourcePath = resolve(sourceArgument);
const outputPath = resolve(outputArgument);
const source = await readFile(sourcePath, 'utf8');
const lines = source.split(/\r?\n/);
const headerIndex = lines.findIndex((line) =>
  line.startsWith('| 序号 | 六十甲子 | 时柱 | 日柱 | 月柱 | 年柱 |'),
);
if (headerIndex < 0) throw new Error('四柱特质表头不存在');

const rows: PositionCopyRow[] = [];
for (const line of lines.slice(headerIndex + 2)) {
  if (!line.startsWith('|')) break;
  const cells = line
    .slice(1, -1)
    .split('|')
    .map((cell) => cell.trim());
  if (cells.length !== 6 || !/^\d+$/.test(cells[0] ?? '')) continue;
  const [sequence, card, hour, day, month, year] = cells;
  if (!sequence || !card || !hour || !day || !month || !year) {
    throw new Error(`四柱特质行不完整：${line}`);
  }
  rows.push({ sequence: Number(sequence), card, hour, day, month, year });
}

if (rows.length !== 60 || new Set(rows.map((row) => row.card)).size !== 60) {
  throw new Error(`四柱特质必须包含 60 个唯一甲子，实际 ${rows.length}`);
}
for (const row of rows) {
  for (const position of ['hour', 'day', 'month', 'year'] as const) {
    if (!row[position]) throw new Error(`${row.card}.${position} 文案为空`);
  }
}

const tableSource = lines.slice(headerIndex, headerIndex + 62).join('\n');
const checksum = createHash('sha256').update(tableSource).digest('hex');
const serializedRows = rows
  .map(
    ({ card, hour, day, month, year }) =>
      `  ${JSON.stringify(card)}: { hour: ${JSON.stringify(hour)}, day: ${JSON.stringify(day)}, month: ${JSON.stringify(month)}, year: ${JSON.stringify(year)} },`,
  )
  .join('\n');

const prettierConfig = await resolveConfig(outputPath);
const output = await format(
  `// Generated by backend/scripts/profile-first-look/build-position-copy.ts.\n// Source: 连山易知识/wiki/知识/06.六十甲子表.md#四柱特质\n\nimport type { ProfileFirstLookPosition } from '@satori/application';\n\nexport const PROFILE_POSITION_COPY_SOURCE_SHA256 = ${JSON.stringify(checksum)};\n\nexport const PROFILE_POSITION_COPY = {\n${serializedRows}\n} as const satisfies Record<string, Record<ProfileFirstLookPosition, string>>;\n`,
  { ...prettierConfig, filepath: outputPath },
);

await writeFile(outputPath, output, 'utf8');
console.log(JSON.stringify({ sourcePath, outputPath, cards: rows.length, cells: rows.length * 4, checksum }));
